name: roi_tracking
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - pandas>=2.0
  - jupyterlab
  - ipykernel
  - onnx
  - pip
  - pip:
      - roicat[all]
