"""
Validate task event timing against raw voltage and dF/F frame timing.

This pipeline is for closed-loop two-photon sessions where:

* ``orientations_logger.csv`` contains Bonsai timestamps for START/END,
  StimStart/StimEnd, photodiode state changes, and wheel encoder values.
* ``orientations_orientations0.csv`` contains the stimulus parameters and IDs
  actually generated by Bonsai for the motor-dependent second block.
* ``*VoltageRecording*.csv`` contains the raw analog Prairie voltage inputs.
* ``raw_voltages.h5`` contains the processed/binarized voltage streams.
* ``qc_results/dff.h5`` contains dF/F traces.

The important design choice is that block 2 uses the Bonsai output CSV, not the
planned task CSV, because block 2 depends on the mouse behavior and Bonsai
generated the actual performed stimulus stream online.

The validator produces:

* a performed block-2 event table with stimulus parameters, logger start/end
  times, and nearest dF/F frame index;
* a trial-level analysis table with standard 0 deg trial starts and oddball
  trials for downstream dF/F alignment;
* high-level validation checks;
* dF/F length and imaging-voltage checks using the raw Prairie CSV Input 3
  scope-exposure channel as the primary frame source;
* raw Prairie voltage channel health;
* processed HDF5 voltage channel health as a secondary comparison;
* START/END alignment to voltage edges.

This does not claim that every stimulus has a hardware photodiode voltage pulse.
For this session, the physical photodiode input has only one pulse, so per-event
hardware-photodiode validation is flagged as unavailable/warning. Event-to-dF/F
alignment is therefore based on Bonsai logger event timestamps mapped to the
raw Prairie VoltageRecording CSV Input 3 scope-exposure train. The processed
HDF5 voltage channels are still summarized as a comparison, but they are not
the primary frame source when the raw CSV is available.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import h5py
import numpy as np
import pandas as pd


TASK_CSV = "sensorimotor_mismatch_example.csv"
BONSAI_OUTPUT_CSV = "orientations_orientations0.csv"
LOGGER_CSV = "orientations_logger.csv"
RAW_VOLTAGES_H5 = "raw_voltages.h5"
DFF_H5 = "qc_results/dff.h5"
MOVE_OFFSET_H5 = "move_offset.h5"
OPS_NPY = "ops.npy"

EVENT_TABLE_CSV = "block2_performed_events_with_dff_frames.csv"
ANALYSIS_TRIAL_CSV = "block2_analysis_trials_with_dff_frames.csv"
VALIDATION_CHECKS_CSV = "event_alignment_validation_checks.csv"
DFF_LENGTH_CSV = "dff_voltage_length_validation.csv"
RAW_H5_HEALTH_CSV = "raw_h5_voltage_channel_health.csv"
PHYSICAL_INPUT_HEALTH_CSV = "physical_voltage_input_health.csv"
START_END_ALIGNMENT_CSV = "logger_start_end_voltage_alignment.csv"
STIM_DURATION_CSV = "logger_stim_duration_summary.csv"
STIM_DURATION_OUTLIERS_CSV = "logger_stim_duration_outliers.csv"
REPORT_MD = "event_alignment_validation_report.md"


RENAME_TO_CANONICAL = {
    "BlockNumber": "Block_Number",
    "BlockLabel": "Block_Label",
    "TrialNumber": "Trial_Number",
    "SequenceNumber": "Sequence_Number",
    "TrialInSequence": "Trial_In_Sequence",
    "SpatialFrequency": "Spatial_Frequency",
    "TemporalFrequency": "Temporal_Frequency",
    "TrialType": "Trial_Type",
    "BlockType": "Block_Type",
}


RAW_H5_CHANNELS = {
    "raw/vol_img": {
        "role": "Scope exposure / 2P imaging frame TTL",
        "kind": "ttl_train",
        "threshold": 0.5,
    },
    "raw/vol_flir": {
        "role": "FLIR output / camera strobe / scope GPIO",
        "kind": "ttl_train",
        "threshold": 0.5,
    },
    "raw/vol_hifi": {
        "role": "HiFi TTL",
        "kind": "ttl_events",
        "threshold": 0.5,
    },
    "raw/vol_stim_aud": {
        "role": "HiFi audio waveform",
        "kind": "analog",
        "threshold": None,
    },
    "raw/vol_pmt": {
        "role": "Physical Input 6, encoder phase A in wiring diagram",
        "kind": "ttl_train",
        "threshold": 0.5,
    },
    "raw/vol_led": {
        "role": "Physical Input 7, encoder phase B in wiring diagram",
        "kind": "ttl_train",
        "threshold": 0.5,
    },
    "raw/vol_2p_stim": {
        "role": "2P stim trigger, optional/unused in this session",
        "kind": "optional_ttl",
        "threshold": 0.5,
    },
    "raw/vol_stim_vis": {
        "role": "Visual stimulus/photodiode processed channel, optional",
        "kind": "optional_ttl",
        "threshold": 0.5,
    },
    "raw/vol_start": {
        "role": "Start/trial trigger, optional/unused in this session",
        "kind": "optional_ttl",
        "threshold": 0.5,
    },
}


PHYSICAL_INPUTS = {
    " Input 0": {"role": "Trial sync / EBC", "kind": "ttl", "threshold": 2.5},
    " Input 1": {"role": "Photodiode", "kind": "ttl", "threshold": 2.5},
    " Input 2": {"role": "HiFi TTL", "kind": "ttl", "threshold": 0.5},
    " Input 3": {"role": "Scope exposure", "kind": "ttl", "threshold": 2.5},
    " Input 4": {"role": "HiFi audio waveform", "kind": "analog", "threshold": None},
    " Input 5": {"role": "FLIR output / camera strobe", "kind": "ttl", "threshold": 1.5},
    " Input 6": {"role": "Encoder phase A", "kind": "ttl", "threshold": 2.5},
    " Input 7": {"role": "Encoder phase B", "kind": "ttl", "threshold": 2.5},
}


PRIMARY_SCOPE_INPUT = " Input 3"
START_END_CSV_INPUTS = [" Input 3", " Input 5", " Input 6", " Input 7"]


ANALYSIS_CONDITION_BY_TRIAL_TYPE = {
    "motor_omission": "omission",
    "motor_halt": "halt",
    "motor_orientation_90": "orientation_90",
    "motor_orientation_45": "orientation_45",
}


@dataclass(frozen=True)
class EventAlignmentValidationResult:
    """Paths and summary tables produced by ``run_event_alignment_validation``."""

    output_dir: Path
    event_table_path: Path
    analysis_trial_table_path: Path
    validation_checks_path: Path
    dff_length_path: Path
    raw_h5_health_path: Path
    physical_input_health_path: Optional[Path]
    start_end_alignment_path: Path
    stim_duration_summary_path: Path
    stim_duration_outliers_path: Path
    report_path: Path
    event_table: pd.DataFrame
    analysis_trial_table: pd.DataFrame
    validation_checks: pd.DataFrame
    dff_length_checks: pd.DataFrame
    raw_h5_health: pd.DataFrame
    physical_input_health: Optional[pd.DataFrame]
    start_end_alignment: pd.DataFrame
    stim_duration_summary: pd.DataFrame
    stim_duration_outliers: pd.DataFrame


def status(ok: bool, warn: bool = False) -> str:
    """Return OK/WARN/FAIL status."""
    if ok:
        return "OK"
    return "WARN" if warn else "FAIL"


def load_voltage_time_seconds(h5: h5py.File) -> tuple[np.ndarray, float]:
    """Load voltage time as seconds and return the inferred sample rate."""
    t_raw = np.asarray(h5["raw/vol_time"])
    dt = float(np.median(np.diff(t_raw[: min(10000, len(t_raw))])))
    # Prairie voltage time here is in ms. Use this heuristic to keep the
    # function robust for files already stored in seconds.
    time_scale = 0.001 if dt > 0.01 else 1.0
    t_sec = t_raw * time_scale
    fs = 1.0 / float(np.median(np.diff(t_sec[: min(10000, len(t_sec))])))
    return t_sec, fs


def detect_edges(signal: np.ndarray, threshold: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return digital state, rising edge indices, and falling edge indices."""
    digital = signal > threshold
    rising = np.flatnonzero((~digital[:-1]) & digital[1:]) + 1
    falling = np.flatnonzero(digital[:-1] & (~digital[1:])) + 1
    return digital, rising, falling


def nearest_indices(sorted_values: np.ndarray, query_values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Find nearest indices in a sorted 1D array for each query value."""
    idx = np.searchsorted(sorted_values, query_values)
    idx0 = np.clip(idx - 1, 0, len(sorted_values) - 1)
    idx1 = np.clip(idx, 0, len(sorted_values) - 1)
    choose_right = np.abs(sorted_values[idx1] - query_values) < np.abs(sorted_values[idx0] - query_values)
    nearest = np.where(choose_right, idx1, idx0)
    deltas = query_values - sorted_values[nearest]
    return nearest, deltas


def load_bonsai_output(path: Path) -> pd.DataFrame:
    """Load Bonsai output stimulus parameters with canonical column names."""
    df = pd.read_csv(path).rename(columns=RENAME_TO_CANONICAL)
    required = ["Id", "Trial_Number", "Trial_Type", "Block_Number", "Block_Type", "Duration"]
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(f"Bonsai output CSV is missing columns: {missing}")
    return df


def parse_logger(path: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load logger and extract StimStart/StimEnd/marker tables."""
    logger = pd.read_csv(path)
    values = logger["Value"].astype(str)

    starts = logger.loc[values.str.startswith("StimStart-"), ["Frame", "Timestamp", "Value"]].copy()
    starts["Id"] = starts["Value"].str.replace("StimStart-", "", regex=False)
    starts = starts.rename(columns={"Frame": "Logger_Start_Frame", "Timestamp": "Stim_Start_sec"})

    ends = logger.loc[values.str.startswith("StimEnd-"), ["Frame", "Timestamp", "Value"]].copy()
    ends["Id"] = ends["Value"].str.replace("StimEnd-", "", regex=False)
    ends = ends.rename(columns={"Frame": "Logger_End_Frame", "Timestamp": "Stim_End_sec"})

    markers = logger.loc[values.isin(["START", "END", "EndFrame"]), ["Frame", "Timestamp", "Value"]].copy()
    photodiode = logger.loc[values.isin(["Photodiode-0", "Photodiode-1"]), ["Frame", "Timestamp", "Value"]].copy()
    return logger, starts, ends, markers, photodiode


def build_performed_event_table(
    bonsai_output: pd.DataFrame,
    starts: pd.DataFrame,
    ends: pd.DataFrame,
    imaging_frame_times: np.ndarray,
    dff_nframes: int,
    imaging_frame_source: str,
) -> pd.DataFrame:
    """Merge Bonsai output rows with logger timing and nearest dF/F frame."""
    events = bonsai_output.merge(
        starts[["Id", "Logger_Start_Frame", "Stim_Start_sec"]],
        on="Id",
        how="left",
        validate="one_to_one",
    ).merge(
        ends[["Id", "Logger_End_Frame", "Stim_End_sec"]],
        on="Id",
        how="left",
        validate="one_to_one",
    )
    events["Logger_Duration_sec"] = events["Stim_End_sec"] - events["Stim_Start_sec"]

    usable_frame_times = imaging_frame_times[:dff_nframes]
    nearest_frame, delta = nearest_indices(usable_frame_times, events["Stim_Start_sec"].to_numpy())
    events["Nearest_Dff_Frame"] = nearest_frame
    events["Nearest_Dff_Time_sec"] = usable_frame_times[nearest_frame]
    events["Stim_To_Dff_Frame_Delta_sec"] = delta
    events["Nearest_Dff_Frame_In_Range"] = (events["Nearest_Dff_Frame"] >= 0) & (events["Nearest_Dff_Frame"] < dff_nframes)
    events["Imaging_Frame_Source"] = imaging_frame_source
    events["Imaging_Frame_Edge_Count"] = int(len(imaging_frame_times))
    return events


def add_duration_qc(events: pd.DataFrame, tolerance_sec: float = 0.020) -> pd.DataFrame:
    """Add logger-vs-CSV duration error and outlier columns."""
    events = events.copy()
    events["Duration_Error_sec"] = events["Logger_Duration_sec"] - pd.to_numeric(events["Duration"], errors="coerce")
    events["Duration_Outlier"] = events["Duration_Error_sec"].abs() > tolerance_sec
    return events


def summarize_stim_durations(events: pd.DataFrame, tolerance_sec: float = 0.020) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Summarize logger stimulus durations and identify duration outliers."""
    if "Duration_Outlier" not in events or "Duration_Error_sec" not in events:
        events = add_duration_qc(events, tolerance_sec=tolerance_sec)

    summary = (
        events.groupby("Trial_Type", dropna=False)
        .agg(
            count=("Id", "size"),
            expected_duration_sec=("Duration", "median"),
            logger_duration_median_sec=("Logger_Duration_sec", "median"),
            logger_duration_min_sec=("Logger_Duration_sec", "min"),
            logger_duration_max_sec=("Logger_Duration_sec", "max"),
            median_error_sec=("Duration_Error_sec", "median"),
            max_abs_error_sec=("Duration_Error_sec", lambda x: x.abs().max()),
            outliers=("Duration_Outlier", "sum"),
        )
        .reset_index()
    )
    outliers = events.loc[
        events["Duration_Outlier"],
        [
            "Trial_Number",
            "Trial_Type",
            "Id",
            "Duration",
            "Logger_Duration_sec",
            "Duration_Error_sec",
            "Stim_Start_sec",
            "Stim_End_sec",
        ],
    ].copy()
    return summary, outliers


def orientation_to_degrees(events: pd.DataFrame) -> pd.Series:
    """Return orientation in degrees, accepting radians or degrees."""
    orientation = pd.to_numeric(events["Orientation"], errors="coerce")
    finite = orientation.dropna().abs()
    if not finite.empty and finite.max() <= 2 * np.pi + 1e-6:
        return np.rad2deg(orientation)
    return orientation


def nearest_distance_to_times(query: np.ndarray, reference: np.ndarray) -> np.ndarray:
    """Return nearest absolute distance from each query time to reference times."""
    if len(reference) == 0:
        return np.full(len(query), np.inf, dtype=float)
    reference = np.sort(np.asarray(reference, dtype=float))
    idx = np.searchsorted(reference, query)
    left = reference[np.clip(idx - 1, 0, len(reference) - 1)]
    right = reference[np.clip(idx, 0, len(reference) - 1)]
    return np.minimum(np.abs(query - left), np.abs(query - right))


def evenly_spaced_rows(df: pd.DataFrame, n_rows: int) -> pd.DataFrame:
    """Select deterministic evenly spaced rows from a sorted DataFrame."""
    if n_rows <= 0 or df.empty:
        return df.iloc[0:0].copy()
    if n_rows >= len(df):
        return df.copy()
    positions = np.linspace(0, len(df) - 1, n_rows)
    indices = np.unique(np.round(positions).astype(int))
    if len(indices) < n_rows:
        remaining = np.setdiff1d(np.arange(len(df)), indices, assume_unique=False)
        indices = np.sort(np.concatenate([indices, remaining[: n_rows - len(indices)]]))
    return df.iloc[indices[:n_rows]].copy()


def standard_trial_starts_between_oddballs(events: pd.DataFrame) -> pd.DataFrame:
    """Return first standard 0 deg start in each interval between oddballs.

    The Bonsai output has one row per short visual presentation. For standard
    0 deg trial alignment, a trial is treated as the start of a standard bout
    bounded by two consecutive motor-oddball rows. Each selected row is the
    first valid standard ``StimStart`` after the previous oddball and before
    the next oddball.
    """
    events = events.sort_values("Stim_Start_sec").reset_index(drop=True).copy()
    if "Duration_Outlier" in events:
        events = events[~events["Duration_Outlier"]].reset_index(drop=True)
    if "Orientation_Mod180" not in events:
        events["Orientation_Deg"] = orientation_to_degrees(events).round(6)
        events["Orientation_Mod180"] = np.mod(events["Orientation_Deg"], 180)

    oddballs = events[events["Trial_Type"].isin(ANALYSIS_CONDITION_BY_TRIAL_TYPE)].reset_index(drop=True)
    rows = []
    for oddball_index in range(len(oddballs) - 1):
        previous_oddball = oddballs.iloc[oddball_index]
        next_oddball = oddballs.iloc[oddball_index + 1]
        in_interval = (
            (events["Stim_Start_sec"] > previous_oddball["Stim_Start_sec"])
            & (events["Stim_Start_sec"] < next_oddball["Stim_Start_sec"])
            & events["Trial_Type"].eq("standard")
            & np.isclose(events["Orientation_Mod180"], 0.0, atol=1e-4)
        )
        candidates = events.loc[in_interval].sort_values("Stim_Start_sec")
        if candidates.empty:
            continue
        row = candidates.iloc[0].copy()
        row["Previous_Oddball_Trial_Type"] = previous_oddball["Trial_Type"]
        row["Previous_Oddball_Start_sec"] = previous_oddball["Stim_Start_sec"]
        row["Next_Oddball_Trial_Type"] = next_oddball["Trial_Type"]
        row["Next_Oddball_Start_sec"] = next_oddball["Stim_Start_sec"]
        row["Inter_Oddball_Interval_sec"] = next_oddball["Stim_Start_sec"] - previous_oddball["Stim_Start_sec"]
        rows.append(row)

    if not rows:
        return events.iloc[0:0].copy()
    out = pd.DataFrame(rows).reset_index(drop=True)
    out["Standard_Trial_Definition"] = "first standard 0 deg StimStart between consecutive oddballs"
    return out


def build_analysis_trial_table(
    events: pd.DataFrame,
    standard_exclusion_sec: float = 1.0,
) -> pd.DataFrame:
    """Build the trial-level table for neural alignment.

    The Bonsai output contains one UUID-paired ``StimStart``/``StimEnd`` row
    per visual frame update during standard closed-loop visual flow. A trial
    for neural analysis is a stimulus presentation, not one frame update:

    * contiguous standard frame-update rows are collapsed into one standard
      presentation;
    * each non-standard motor oddball row is kept as its own presentation.
    """
    events = events.copy()
    if "Duration_Outlier" not in events:
        events = add_duration_qc(events)
    events["Orientation_Deg"] = orientation_to_degrees(events).round(6)
    events["Orientation_Mod180"] = np.mod(events["Orientation_Deg"], 180)
    events["Source_Event_Row"] = np.arange(len(events), dtype=int)

    valid = events[
        events["Stim_Start_sec"].notna()
        & events["Stim_End_sec"].notna()
        & events["Id"].notna()
    ].sort_values("Stim_Start_sec").reset_index(drop=True).copy()
    if valid.empty:
        return valid

    trial_type = valid["Trial_Type"].astype(str)
    new_presentation = trial_type.ne(trial_type.shift()) | trial_type.ne("standard")
    valid["Presentation_Run"] = new_presentation.cumsum()

    first_cols = [
        "Contrast",
        "Delay",
        "DiameterX",
        "DiameterY",
        "Orientation",
        "Spatial_Frequency",
        "Temporal_Frequency",
        "X",
        "Y",
        "Phase",
        "Trial_Type",
        "Block_Type",
        "Block_Number",
        "Block_Label",
        "Sequence_Number",
        "Trial_In_Sequence",
        "Stim_Start_sec",
        "Logger_Start_Frame",
        "Nearest_Dff_Frame",
        "Nearest_Dff_Time_sec",
        "Stim_To_Dff_Frame_Delta_sec",
        "Nearest_Dff_Frame_In_Range",
        "Imaging_Frame_Source",
        "Imaging_Frame_Edge_Count",
        "Orientation_Deg",
        "Orientation_Mod180",
        "Source_Event_Row",
    ]
    agg = {col: (col, "first") for col in first_cols if col in valid.columns}
    agg.update(
        {
            "Id": ("Id", "first"),
            "Presentation_Start_Id": ("Id", "first"),
            "Presentation_End_Id": ("Id", "last"),
            "Trial_Number": ("Trial_Number", "first"),
            "Presentation_End_Trial_Number": ("Trial_Number", "last"),
            "Stim_End_sec": ("Stim_End_sec", "last"),
            "Logger_End_Frame": ("Logger_End_Frame", "last"),
            "Duration": ("Duration", "sum"),
            "Logger_Duration_sec": ("Logger_Duration_sec", "sum"),
            "Duration_Error_sec": ("Duration_Error_sec", "sum"),
            "Duration_Outlier": ("Duration_Outlier", "any"),
            "Source_Update_Rows": ("Id", "size"),
            "Source_Event_End_Row": ("Source_Event_Row", "last"),
        }
    )

    analysis = valid.groupby("Presentation_Run", as_index=False).agg(**agg)
    if analysis.empty:
        return analysis

    analysis["Analysis_Condition"] = analysis["Trial_Type"].map(ANALYSIS_CONDITION_BY_TRIAL_TYPE)
    analysis.loc[
        analysis["Analysis_Condition"].isna()
        & analysis["Trial_Type"].eq("standard")
        & np.isclose(analysis["Orientation_Mod180"], 0.0, atol=1e-4),
        "Analysis_Condition",
    ] = "standard_control"
    analysis["Analysis_Condition"] = analysis["Analysis_Condition"].fillna(analysis["Trial_Type"].astype(str))
    analysis["Selection_Rule"] = np.where(
        analysis["Trial_Type"].eq("standard"),
        "contiguous standard frame-update presentation",
        "single motor-oddball StimStart/StimEnd presentation",
    )

    condition_order = {
        "standard_control": 0,
        "omission": 1,
        "halt": 2,
        "orientation_90": 3,
        "orientation_45": 4,
    }
    analysis["Analysis_Condition_Order"] = analysis["Analysis_Condition"].map(condition_order).fillna(99).astype(int)
    analysis = analysis.sort_values(["Stim_Start_sec", "Analysis_Condition_Order"]).reset_index(drop=True)
    analysis["Analysis_Trial"] = np.arange(1, len(analysis) + 1, dtype=int)
    analysis["Analysis_Trial_In_Condition"] = analysis.groupby("Analysis_Condition").cumcount() + 1
    analysis["Is_Analysis_Trial"] = True

    front_cols = [
        "Analysis_Trial",
        "Analysis_Trial_In_Condition",
        "Analysis_Condition",
        "Analysis_Condition_Order",
        "Selection_Rule",
        "Is_Analysis_Trial",
        "Source_Update_Rows",
        "Source_Event_Row",
        "Source_Event_End_Row",
        "Presentation_Start_Id",
        "Presentation_End_Id",
    ]
    remaining = [col for col in analysis.columns if col not in front_cols]
    return analysis[front_cols + remaining]


def summarize_raw_h5_voltage_channels(
    data_dir: Path,
    dff_nframes: int,
) -> tuple[pd.DataFrame, np.ndarray, np.ndarray, float]:
    """Summarize raw HDF5 voltage channels and return imaging frame times."""
    rows = []
    raw_path = data_dir / RAW_VOLTAGES_H5
    with h5py.File(raw_path, "r") as h5:
        t_sec, voltage_fs = load_voltage_time_seconds(h5)
        imaging_frame_times = np.array([], dtype=float)
        imaging_rising = np.array([], dtype=int)

        for key, spec in RAW_H5_CHANNELS.items():
            if key not in h5:
                rows.append({"channel": key, "role": spec["role"], "status": "FAIL", "note": "missing"})
                continue

            x = np.asarray(h5[key])
            row = {
                "channel": key,
                "role": spec["role"],
                "kind": spec["kind"],
                "n_samples": int(len(x)),
                "min": float(np.nanmin(x)),
                "mean": float(np.nanmean(x)),
                "max": float(np.nanmax(x)),
                "std": float(np.nanstd(x)),
                "threshold": spec["threshold"],
                "rising_edges": np.nan,
                "falling_edges": np.nan,
                "median_period_sec": np.nan,
                "edge_rate_hz": np.nan,
                "high_fraction": np.nan,
                "status": "OK",
                "note": "",
            }

            if spec["kind"] == "analog":
                row["status"] = "OK" if row["std"] > 1e-4 else "WARN"
                row["note"] = "analog waveform active" if row["status"] == "OK" else "analog waveform appears flat"
            else:
                threshold = float(spec["threshold"])
                digital, rising, falling = detect_edges(x, threshold)
                row["rising_edges"] = int(len(rising))
                row["falling_edges"] = int(len(falling))
                row["high_fraction"] = float(digital.mean())
                if len(rising) > 2:
                    periods = np.diff(t_sec[rising])
                    row["median_period_sec"] = float(np.median(periods))
                    row["edge_rate_hz"] = float(1.0 / np.median(periods))

                if key == "raw/vol_img":
                    imaging_rising = rising
                    imaging_frame_times = t_sec[rising]
                    diff = abs(len(rising) - dff_nframes)
                    row["status"] = "OK" if diff <= 5 else "WARN"
                    row["note"] = f"scope exposure edges minus dF/F frames = {len(rising) - dff_nframes:+d}"
                elif spec["kind"] == "ttl_train":
                    row["status"] = "OK" if len(rising) > 100 else "WARN"
                    row["note"] = "active TTL train" if row["status"] == "OK" else "few/no TTL edges"
                elif spec["kind"] == "ttl_events":
                    row["status"] = "OK" if len(rising) > 0 else "WARN"
                    row["note"] = "event TTL active" if row["status"] == "OK" else "no event TTL edges"
                else:
                    row["status"] = "INFO" if len(rising) == 0 else "OK"
                    row["note"] = "optional channel unused/flat" if len(rising) == 0 else "optional channel has edges"

            rows.append(row)

    return pd.DataFrame(rows), imaging_rising, imaging_frame_times, voltage_fs


def h5_edge_times_for_start_end(data_dir: Path) -> dict[str, dict[str, np.ndarray]]:
    """Collect processed HDF5 edge times for fallback marker alignment."""
    edge_times: dict[str, dict[str, np.ndarray]] = {}
    raw_path = data_dir / RAW_VOLTAGES_H5
    with h5py.File(raw_path, "r") as h5:
        t_sec, _ = load_voltage_time_seconds(h5)
        for channel in ["raw/vol_img", "raw/vol_flir", "raw/vol_led", "raw/vol_pmt"]:
            if channel not in h5:
                continue
            spec = RAW_H5_CHANNELS[channel]
            x = np.asarray(h5[channel])
            _, rising, falling = detect_edges(x, float(spec["threshold"]))
            edge_times[channel] = {
                "rising": t_sec[rising],
                "falling": t_sec[falling],
            }
    return edge_times


def load_dff_metadata(data_dir: Path) -> dict:
    """Load dF/F shape, Suite2p ops metadata, and movement-offset length."""
    dff_path = data_dir / DFF_H5
    with h5py.File(dff_path, "r") as h5:
        dff_shape = tuple(h5["dff"].shape)

    ops = np.load(data_dir / OPS_NPY, allow_pickle=True).item() if (data_dir / OPS_NPY).exists() else {}
    fs = float(ops.get("fs", np.nan))
    ops_nframes = int(ops.get("nframes", -1)) if "nframes" in ops else np.nan

    move_lengths = {}
    move_path = data_dir / MOVE_OFFSET_H5
    if move_path.exists():
        with h5py.File(move_path, "r") as h5:
            for key in h5.keys():
                move_lengths[key] = int(h5[key].shape[0])

    return {
        "dff_shape": dff_shape,
        "dff_n_rois": int(dff_shape[0]),
        "dff_nframes": int(dff_shape[1]),
        "suite2p_fs": fs,
        "ops_nframes": ops_nframes,
        "dff_duration_sec": float(dff_shape[1] / fs) if np.isfinite(fs) and fs > 0 else np.nan,
        "move_lengths": move_lengths,
    }


def make_dff_length_checks(
    dff_meta: dict,
    imaging_frame_times: np.ndarray,
    voltage_fs: float,
    voltage_duration_sec: float,
    imaging_frame_source: str,
) -> pd.DataFrame:
    """Create checks linking dF/F length to imaging voltage frame count."""
    dff_nframes = dff_meta["dff_nframes"]
    ops_nframes = dff_meta["ops_nframes"]
    scope_edges = int(len(imaging_frame_times))
    edge_diff = scope_edges - dff_nframes
    median_period = float(np.median(np.diff(imaging_frame_times))) if len(imaging_frame_times) > 2 else np.nan

    rows = [
        {
            "check": "scope exposure frame source",
            "status": status("VoltageRecording CSV" in imaging_frame_source, warn=True),
            "value": imaging_frame_source,
        },
        {
            "check": "dF/F frame count equals Suite2p ops nframes",
            "status": status(dff_nframes == ops_nframes),
            "value": f"dff={dff_nframes}, ops={ops_nframes}",
        },
        {
            "check": "scope exposure voltage edge count matches dF/F frames",
            "status": status(abs(edge_diff) <= 5, warn=True),
            "value": f"source={imaging_frame_source}; scope_edges={scope_edges}, dff_frames={dff_nframes}, diff={edge_diff:+d}",
        },
        {
            "check": "scope exposure median frame rate is near Suite2p fs",
            "status": status(np.isfinite(median_period) and abs((1.0 / median_period) - dff_meta["suite2p_fs"]) < 0.2, warn=True),
            "value": f"voltage_fs={1.0 / median_period:.4f} Hz, suite2p_fs={dff_meta['suite2p_fs']:.4f} Hz",
        },
        {
            "check": "raw voltage duration covers dF/F duration",
            "status": status(voltage_duration_sec >= dff_meta["dff_duration_sec"], warn=True),
            "value": f"voltage={voltage_duration_sec:.3f} sec, dff={dff_meta['dff_duration_sec']:.3f} sec",
        },
    ]

    for key, length in dff_meta["move_lengths"].items():
        rows.append(
            {
                "check": f"movement offset {key} length equals dF/F frames",
                "status": status(length == dff_nframes, warn=True),
                "value": f"{key}={length}, dff={dff_nframes}",
            }
        )
    return pd.DataFrame(rows)


def align_start_end_to_voltage(
    markers: pd.DataFrame,
    voltage_edge_times: dict[str, dict[str, np.ndarray]],
    voltage_source: str,
) -> pd.DataFrame:
    """Find nearest voltage TTL edges to logger START/END markers."""
    marker_rows = markers[markers["Value"].isin(["START", "END"])].copy()
    if marker_rows.empty:
        return pd.DataFrame()

    rows = []
    for channel, edge_sets in voltage_edge_times.items():
        for marker in marker_rows.itertuples(index=False):
            for edge_name in ["rising", "falling"]:
                edge_times = np.asarray(edge_sets.get(edge_name, []), dtype=float)
                if len(edge_times) == 0:
                    continue
                nearest, delta = nearest_indices(edge_times, np.array([marker.Timestamp], dtype=float))
                rows.append(
                    {
                        "marker": marker.Value,
                        "logger_timestamp_sec": float(marker.Timestamp),
                        "voltage_source": voltage_source,
                        "voltage_channel": channel.strip(),
                        "edge_type": edge_name,
                        "nearest_voltage_edge_sec": float(edge_times[nearest[0]]),
                        "logger_minus_voltage_sec": float(delta[0]),
                        "abs_error_ms": float(abs(delta[0]) * 1000),
                        "status": "OK" if abs(delta[0]) <= 0.020 else "WARN",
                    }
                )
    return pd.DataFrame(rows)


def find_voltage_csv(data_dir: Path) -> Optional[Path]:
    """Find the Prairie voltage recording CSV."""
    matches = sorted(data_dir.glob("*VoltageRecording*.csv"))
    return matches[0] if matches else None


def infer_ttl_threshold(min_value: float, max_value: float, fallback: Optional[float]) -> tuple[float, str]:
    """Infer a TTL threshold from raw analog voltage range."""
    if np.isfinite(min_value) and np.isfinite(max_value) and (max_value - min_value) > 0.5:
        return float(min_value + 0.5 * (max_value - min_value)), "adaptive_midrange"
    if fallback is None:
        return np.nan, "not_applicable"
    return float(fallback), "fallback"


def collect_voltage_csv_stats(
    voltage_csv: Path,
    chunksize: int,
) -> tuple[dict[str, dict], float, float, float]:
    """First pass over the raw Prairie CSV to collect stats and sample rate."""
    usecols = ["Time(ms)"] + list(PHYSICAL_INPUTS.keys())
    states = {
        col: {"min": np.inf, "max": -np.inf, "sum": 0.0, "sum2": 0.0, "n": 0}
        for col in PHYSICAL_INPUTS
    }
    first_time = np.nan
    last_time = np.nan
    first_dt = np.nan
    for chunk in pd.read_csv(voltage_csv, usecols=usecols, chunksize=chunksize):
        t_sec = chunk["Time(ms)"].to_numpy(dtype=float) / 1000.0
        if np.isnan(first_time):
            first_time = float(t_sec[0])
            first_dt = float(np.median(np.diff(t_sec[: min(10000, len(t_sec))])))
        last_time = float(t_sec[-1])

        for col in PHYSICAL_INPUTS:
            x = chunk[col].to_numpy(dtype=float)
            state = states[col]
            state["min"] = min(state["min"], float(np.nanmin(x)))
            state["max"] = max(state["max"], float(np.nanmax(x)))
            state["sum"] += float(np.nansum(x))
            state["sum2"] += float(np.nansum(x * x))
            state["n"] += len(x)

    voltage_fs = 1.0 / first_dt if np.isfinite(first_dt) and first_dt > 0 else np.nan
    return states, first_time, last_time, voltage_fs


def scan_physical_voltage_inputs_with_edges(
    voltage_csv: Path,
    logger_photodiode_count: int,
    chunksize: int = 500_000,
    collect_edge_inputs: Optional[list[str]] = None,
) -> tuple[pd.DataFrame, dict[str, dict[str, np.ndarray]], float, float]:
    """Scan raw Prairie CSV, summarize inputs, and collect selected edge times."""
    collect_edge_inputs = collect_edge_inputs or []
    stats, first_time, last_time, voltage_fs = collect_voltage_csv_stats(voltage_csv, chunksize)
    usecols = ["Time(ms)"] + list(PHYSICAL_INPUTS.keys())

    states = {}
    for col, spec in PHYSICAL_INPUTS.items():
        threshold, threshold_source = infer_ttl_threshold(stats[col]["min"], stats[col]["max"], spec["threshold"])
        states[col] = {
            **stats[col],
            "threshold": threshold,
            "threshold_source": threshold_source,
            "rising_edges": 0,
            "falling_edges": 0,
            "high_count": 0,
            "first_rising_sec": np.nan,
            "last_rising_sec": np.nan,
            "prev_digital": None,
        }

    edge_times = {
        col: {"rising": [], "falling": []}
        for col in collect_edge_inputs
    }

    for chunk in pd.read_csv(voltage_csv, usecols=usecols, chunksize=chunksize):
        t_sec = chunk["Time(ms)"].to_numpy(dtype=float) / 1000.0
        for col, spec in PHYSICAL_INPUTS.items():
            if spec["kind"] == "analog":
                continue

            state = states[col]
            threshold = float(state["threshold"])
            x = chunk[col].to_numpy(dtype=float)
            digital = x > threshold
            state["high_count"] += int(digital.sum())

            boundary_rising = state["prev_digital"] is not None and (not state["prev_digital"]) and bool(digital[0])
            boundary_falling = state["prev_digital"] is not None and state["prev_digital"] and (not bool(digital[0]))
            if boundary_rising:
                state["rising_edges"] += 1
                state["first_rising_sec"] = (
                    float(t_sec[0]) if np.isnan(state["first_rising_sec"]) else state["first_rising_sec"]
                )
                state["last_rising_sec"] = float(t_sec[0])
                if col in edge_times:
                    edge_times[col]["rising"].append(np.array([float(t_sec[0])], dtype=float))
            if boundary_falling:
                state["falling_edges"] += 1
                if col in edge_times:
                    edge_times[col]["falling"].append(np.array([float(t_sec[0])], dtype=float))

            rising = np.flatnonzero((~digital[:-1]) & digital[1:]) + 1
            falling = np.flatnonzero(digital[:-1] & (~digital[1:])) + 1
            state["rising_edges"] += int(len(rising))
            state["falling_edges"] += int(len(falling))
            if len(rising):
                state["first_rising_sec"] = (
                    float(t_sec[rising[0]]) if np.isnan(state["first_rising_sec"]) else state["first_rising_sec"]
                )
                state["last_rising_sec"] = float(t_sec[rising[-1]])
            if col in edge_times:
                if len(rising):
                    edge_times[col]["rising"].append(t_sec[rising].astype(float, copy=True))
                if len(falling):
                    edge_times[col]["falling"].append(t_sec[falling].astype(float, copy=True))
            state["prev_digital"] = bool(digital[-1])

    duration_sec = last_time - first_time
    rows = []
    for col, spec in PHYSICAL_INPUTS.items():
        state = states[col]
        mean = state["sum"] / state["n"]
        std = max(state["sum2"] / state["n"] - mean * mean, 0) ** 0.5
        row = {
            "input": col.strip(),
            "role": spec["role"],
            "kind": spec["kind"],
            "threshold": state["threshold"],
            "threshold_source": state["threshold_source"],
            "min": state["min"],
            "mean": mean,
            "max": state["max"],
            "std": std,
            "rising_edges": state["rising_edges"],
            "falling_edges": state["falling_edges"],
            "high_fraction": state["high_count"] / state["n"] if spec["kind"] != "analog" else np.nan,
            "first_rising_sec": state["first_rising_sec"],
            "last_rising_sec": state["last_rising_sec"],
            "status": "OK",
            "note": "",
        }

        if spec["kind"] == "analog":
            row["status"] = "OK" if std > 1e-4 else "WARN"
            row["note"] = "analog input active" if row["status"] == "OK" else "analog input flat"
        elif col == " Input 1":
            enough = state["rising_edges"] + state["falling_edges"] >= max(10, 0.5 * logger_photodiode_count)
            row["status"] = "OK" if enough else "WARN"
            row["note"] = (
                "physical photodiode input has enough transitions"
                if enough
                else f"physical photodiode has too few transitions for per-event validation; logger photodiode events={logger_photodiode_count}"
            )
        elif col == PRIMARY_SCOPE_INPUT:
            row["status"] = "OK" if state["rising_edges"] > 100 else "WARN"
            row["note"] = "raw CSV scope exposure active; primary frame-alignment source" if row["status"] == "OK" else "scope exposure has few/no edges"
        elif col in [" Input 6", " Input 7"]:
            row["status"] = "OK" if state["rising_edges"] > 100 else "WARN"
            row["note"] = "encoder phase active" if row["status"] == "OK" else "encoder phase has few/no edges"
        elif col == " Input 0":
            row["status"] = "INFO" if state["rising_edges"] == 0 else "OK"
            row["note"] = "trial sync input unused/flat" if state["rising_edges"] == 0 else "trial sync has edges"
        else:
            row["status"] = "OK" if state["rising_edges"] > 0 else "WARN"
            row["note"] = "input has edges" if row["status"] == "OK" else "input has no edges"

        rows.append(row)

    for col in edge_times:
        for edge_name in ["rising", "falling"]:
            parts = edge_times[col][edge_name]
            edge_times[col][edge_name] = np.concatenate(parts) if parts else np.array([], dtype=float)

    out = pd.DataFrame(rows)
    out["recording_duration_sec"] = duration_sec
    out["voltage_fs_hz"] = voltage_fs
    return out, edge_times, voltage_fs, duration_sec


def scan_physical_voltage_inputs(
    voltage_csv: Path,
    logger_photodiode_count: int,
    chunksize: int = 500_000,
) -> pd.DataFrame:
    """Scan the large Prairie CSV in chunks and summarize physical input health."""
    health, _, _, _ = scan_physical_voltage_inputs_with_edges(
        voltage_csv,
        logger_photodiode_count=logger_photodiode_count,
        chunksize=chunksize,
    )
    return health


def make_validation_checks(
    *,
    bonsai_output: pd.DataFrame,
    starts: pd.DataFrame,
    ends: pd.DataFrame,
    events: pd.DataFrame,
    markers: pd.DataFrame,
    photodiode: pd.DataFrame,
    dff_length_checks: pd.DataFrame,
    start_end_alignment: pd.DataFrame,
    physical_input_health: Optional[pd.DataFrame],
    imaging_frame_source: str,
    analysis_trial_table: pd.DataFrame,
) -> pd.DataFrame:
    """Create high-level validation checks."""
    bonsai_ids = set(bonsai_output["Id"])
    start_ids = set(starts["Id"])
    end_ids = set(ends["Id"])

    start_end_best = (
        start_end_alignment.groupby("marker")["abs_error_ms"].min().to_dict()
        if not start_end_alignment.empty
        else {}
    )
    max_event_frame_delta_ms = float(events["Stim_To_Dff_Frame_Delta_sec"].abs().max() * 1000)
    all_events_in_frame_range = bool(events["Nearest_Dff_Frame_In_Range"].all())
    source_update_rows = (
        int(analysis_trial_table["Source_Update_Rows"].sum())
        if "Source_Update_Rows" in analysis_trial_table.columns
        else 0
    )

    rows = [
        {
            "check": "Imaging frame alignment uses raw VoltageRecording CSV",
            "status": status("VoltageRecording CSV" in imaging_frame_source, warn=True),
            "value": imaging_frame_source,
        },
        {
            "check": "Bonsai output IDs match logger StimStart IDs",
            "status": status(bonsai_ids == start_ids),
            "value": f"bonsai={len(bonsai_ids)}, starts={len(start_ids)}, missing_from_logger={len(bonsai_ids - start_ids)}, extra_logger={len(start_ids - bonsai_ids)}",
        },
        {
            "check": "Bonsai output IDs match logger StimEnd IDs",
            "status": status(bonsai_ids == end_ids),
            "value": f"bonsai={len(bonsai_ids)}, ends={len(end_ids)}, missing_from_logger={len(bonsai_ids - end_ids)}, extra_logger={len(end_ids - bonsai_ids)}",
        },
        {
            "check": "All performed block-2 events map to a valid dF/F frame",
            "status": status(all_events_in_frame_range),
            "value": f"{events['Nearest_Dff_Frame_In_Range'].sum():,}/{len(events):,}",
        },
        {
            "check": "Presentation-level trial table covers all UUID-paired frame updates",
            "status": status(
                source_update_rows == len(events)
                and source_update_rows == len(bonsai_ids)
                and bonsai_ids == start_ids
                and bonsai_ids == end_ids,
                warn=True,
            ),
            "value": f"presentation_trials={len(analysis_trial_table):,}, source_uuid_frame_updates={source_update_rows:,}, logger_starts={len(start_ids):,}, logger_ends={len(end_ids):,}",
        },
        {
            "check": "Trial-level analysis table contains standard trials and oddballs",
            "status": status(
                {"standard_control", "omission", "halt", "orientation_90", "orientation_45"}.issubset(
                    set(analysis_trial_table.get("Analysis_Condition", pd.Series(dtype=str)))
                ),
                warn=True,
            ),
            "value": ", ".join(
                f"{condition}={count}"
                for condition, count in analysis_trial_table.get("Analysis_Condition", pd.Series(dtype=str)).value_counts().sort_index().items()
            ),
        },
        {
            "check": "Maximum event-start to nearest dF/F frame delta is within half-frame",
            "status": status(max_event_frame_delta_ms <= 17.0, warn=True),
            "value": f"max_abs_delta={max_event_frame_delta_ms:.3f} ms",
        },
        {
            "check": "Logger START marker aligns to a nearby voltage edge",
            "status": status(start_end_best.get("START", np.inf) <= 20.0, warn=True),
            "value": f"best_abs_error_ms={start_end_best.get('START', np.nan):.3f}",
        },
        {
            "check": "Logger END marker aligns to a nearby voltage edge",
            "status": status(start_end_best.get("END", np.inf) <= 20.0, warn=True),
            "value": f"best_abs_error_ms={start_end_best.get('END', np.nan):.3f}",
        },
        {
            "check": "Logger photodiode events exist",
            "status": status(len(photodiode) > 0, warn=True),
            "value": f"{len(photodiode):,} logger photodiode rows",
        },
    ]

    for row in dff_length_checks.to_dict("records"):
        rows.append({"check": row["check"], "status": row["status"], "value": row["value"]})

    if physical_input_health is not None:
        photo = physical_input_health.loc[physical_input_health["input"].eq("Input 1")]
        if not photo.empty:
            row = photo.iloc[0]
            rows.append(
                {
                    "check": "Physical photodiode input is usable for per-event voltage validation",
                    "status": row["status"],
                    "value": f"rising={int(row['rising_edges'])}, falling={int(row['falling_edges'])}; {row['note']}",
                }
            )
    return pd.DataFrame(rows)


def write_markdown_report(
    path: Path,
    validation_checks: pd.DataFrame,
    dff_length_checks: pd.DataFrame,
    raw_h5_health: pd.DataFrame,
    physical_input_health: Optional[pd.DataFrame],
    event_table: pd.DataFrame,
    analysis_trial_table: pd.DataFrame,
) -> None:
    """Write a compact markdown report."""
    def markdown_table(df: pd.DataFrame) -> str:
        """Render a small DataFrame as a markdown table without tabulate."""
        if df.empty:
            return "_No rows._"
        str_df = df.astype(str)
        headers = list(str_df.columns)
        rows = str_df.values.tolist()
        lines = [
            "| " + " | ".join(headers) + " |",
            "| " + " | ".join(["---"] * len(headers)) + " |",
        ]
        for row in rows:
            lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
        return "\n".join(lines)

    lines = [
        "# Event Alignment Validation Report",
        "",
        "## Recommendation",
        "",
        "Use `orientations_orientations0.csv` plus `orientations_logger.csv` for performed block-2 events.",
        "Use the raw Prairie `*VoltageRecording*.csv` `Input 3` scope-exposure edges to map logger event times onto dF/F frame indices.",
        "Use processed `raw_voltages.h5` channels only as a secondary comparison unless the raw CSV is unavailable.",
        "For this session, physical photodiode voltage validation is only usable if the physical photodiode input has enough edges; see the checks table.",
        "",
        "## High-Level Checks",
        "",
        markdown_table(validation_checks),
        "",
        "## dF/F Length Checks",
        "",
        markdown_table(dff_length_checks),
        "",
        "## Raw HDF5 Voltage Health",
        "",
        markdown_table(raw_h5_health[["channel", "role", "rising_edges", "falling_edges", "edge_rate_hz", "status", "note"]]),
        "",
    ]
    if physical_input_health is not None:
        lines.extend(
            [
                "## Physical Voltage Input Health",
                "",
                markdown_table(physical_input_health[["input", "role", "threshold", "threshold_source", "rising_edges", "falling_edges", "status", "note"]]),
                "",
            ]
        )
    lines.extend(
        [
            "## Event Table Summary",
            "",
            f"Performed block-2 UUID-paired frame-update rows: {len(event_table):,}",
            f"Imaging frame source: {event_table['Imaging_Frame_Source'].iloc[0] if 'Imaging_Frame_Source' in event_table else 'not recorded'}",
            f"First event start: {event_table['Stim_Start_sec'].min():.6f} sec",
            f"Last event end: {event_table['Stim_End_sec'].max():.6f} sec",
            f"Nearest dF/F frame range: {int(event_table['Nearest_Dff_Frame'].min())} to {int(event_table['Nearest_Dff_Frame'].max())}",
            "",
            "## Trial-Level Analysis Table",
            "",
            "This table is intended for neural alignment. Each row is one stimulus-presentation trial.",
            "Contiguous standard frame-update rows are collapsed into one standard presentation; each motor oddball row is one presentation.",
            markdown_table(
                analysis_trial_table.groupby("Analysis_Condition", as_index=False)
                .agg(
                    trials=("Analysis_Trial", "size"),
                    source_update_rows=("Source_Update_Rows", "sum"),
                    first_start_sec=("Stim_Start_sec", "min"),
                    last_start_sec=("Stim_Start_sec", "max"),
                    selection_rule=("Selection_Rule", "first"),
                )
            )
            if not analysis_trial_table.empty
            else "_No analysis trials._",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def run_event_alignment_validation(
    data_dir: str | Path,
    output_dir: str | Path | None = None,
    scan_voltage_csv_inputs: bool = True,
) -> EventAlignmentValidationResult:
    """Run event, voltage, and dF/F alignment validation.

    Parameters
    ----------
    data_dir
        Session data directory.
    output_dir
        Directory for validation outputs. Defaults to ``data_dir``.
    scan_voltage_csv_inputs
        If True, scan the large Prairie voltage CSV in chunks to validate the
        physical Input0-Input7 channels shown in the wiring diagram. This takes
        longer but is useful for checking the physical photodiode and encoder
        inputs. Raw HDF5 voltage checks are always run.
    """
    data_dir = Path(data_dir).expanduser().resolve()
    output_dir = data_dir if output_dir is None else Path(output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    bonsai_output = load_bonsai_output(data_dir / BONSAI_OUTPUT_CSV)
    logger, starts, ends, markers, photodiode = parse_logger(data_dir / LOGGER_CSV)
    dff_meta = load_dff_metadata(data_dir)

    raw_h5_health, h5_imaging_rising, h5_imaging_frame_times, h5_voltage_fs = summarize_raw_h5_voltage_channels(
        data_dir,
        dff_nframes=dff_meta["dff_nframes"],
    )

    with h5py.File(data_dir / RAW_VOLTAGES_H5, "r") as h5:
        t_sec, _ = load_voltage_time_seconds(h5)
        h5_voltage_duration_sec = float(t_sec[-1] - t_sec[0])

    physical_input_health = None
    physical_input_health_path = None
    csv_edge_times: dict[str, dict[str, np.ndarray]] = {}
    csv_voltage_fs = np.nan
    csv_voltage_duration_sec = np.nan
    voltage_csv = find_voltage_csv(data_dir)
    if scan_voltage_csv_inputs and voltage_csv is not None:
        physical_input_health, csv_edge_times, csv_voltage_fs, csv_voltage_duration_sec = scan_physical_voltage_inputs_with_edges(
            voltage_csv,
            logger_photodiode_count=len(photodiode),
            collect_edge_inputs=START_END_CSV_INPUTS,
        )
        physical_input_health_path = output_dir / PHYSICAL_INPUT_HEALTH_CSV
        physical_input_health.to_csv(physical_input_health_path, index=False)

    if PRIMARY_SCOPE_INPUT in csv_edge_times and len(csv_edge_times[PRIMARY_SCOPE_INPUT]["rising"]) > 0:
        imaging_frame_times = csv_edge_times[PRIMARY_SCOPE_INPUT]["rising"]
        voltage_fs = csv_voltage_fs
        voltage_duration_sec = csv_voltage_duration_sec
        imaging_frame_source = f"VoltageRecording CSV {PRIMARY_SCOPE_INPUT.strip()} ({voltage_csv.name})"
        start_end_edge_times = csv_edge_times
        start_end_voltage_source = f"VoltageRecording CSV ({voltage_csv.name})"
    else:
        imaging_frame_times = h5_imaging_frame_times
        voltage_fs = h5_voltage_fs
        voltage_duration_sec = h5_voltage_duration_sec
        imaging_frame_source = "processed HDF5 raw/vol_img fallback"
        start_end_edge_times = h5_edge_times_for_start_end(data_dir)
        start_end_voltage_source = "processed HDF5 raw_voltages.h5 fallback"

    if len(imaging_frame_times) == 0:
        raise RuntimeError(
            "Could not detect imaging frame edges from raw VoltageRecording CSV Input 3 "
            "or processed HDF5 raw/vol_img fallback"
        )

    event_table = build_performed_event_table(
        bonsai_output=bonsai_output,
        starts=starts,
        ends=ends,
        imaging_frame_times=imaging_frame_times,
        dff_nframes=dff_meta["dff_nframes"],
        imaging_frame_source=imaging_frame_source,
    )
    event_table = add_duration_qc(event_table)
    analysis_trial_table = build_analysis_trial_table(event_table)
    stim_duration_summary, stim_duration_outliers = summarize_stim_durations(event_table)

    dff_length_checks = make_dff_length_checks(
        dff_meta=dff_meta,
        imaging_frame_times=imaging_frame_times,
        voltage_fs=voltage_fs,
        voltage_duration_sec=voltage_duration_sec,
        imaging_frame_source=imaging_frame_source,
    )
    start_end_alignment = align_start_end_to_voltage(
        markers,
        voltage_edge_times=start_end_edge_times,
        voltage_source=start_end_voltage_source,
    )

    validation_checks = make_validation_checks(
        bonsai_output=bonsai_output,
        starts=starts,
        ends=ends,
        events=event_table,
        markers=markers,
        photodiode=photodiode,
        dff_length_checks=dff_length_checks,
        start_end_alignment=start_end_alignment,
        physical_input_health=physical_input_health,
        imaging_frame_source=imaging_frame_source,
        analysis_trial_table=analysis_trial_table,
    )

    event_table_path = output_dir / EVENT_TABLE_CSV
    analysis_trial_table_path = output_dir / ANALYSIS_TRIAL_CSV
    validation_checks_path = output_dir / VALIDATION_CHECKS_CSV
    dff_length_path = output_dir / DFF_LENGTH_CSV
    raw_h5_health_path = output_dir / RAW_H5_HEALTH_CSV
    start_end_alignment_path = output_dir / START_END_ALIGNMENT_CSV
    stim_duration_summary_path = output_dir / STIM_DURATION_CSV
    stim_duration_outliers_path = output_dir / STIM_DURATION_OUTLIERS_CSV
    report_path = output_dir / REPORT_MD

    event_table.to_csv(event_table_path, index=False)
    analysis_trial_table.to_csv(analysis_trial_table_path, index=False)
    validation_checks.to_csv(validation_checks_path, index=False)
    dff_length_checks.to_csv(dff_length_path, index=False)
    raw_h5_health.to_csv(raw_h5_health_path, index=False)
    start_end_alignment.to_csv(start_end_alignment_path, index=False)
    stim_duration_summary.to_csv(stim_duration_summary_path, index=False)
    stim_duration_outliers.to_csv(stim_duration_outliers_path, index=False)
    write_markdown_report(
        report_path,
        validation_checks=validation_checks,
        dff_length_checks=dff_length_checks,
        raw_h5_health=raw_h5_health,
        physical_input_health=physical_input_health,
        event_table=event_table,
        analysis_trial_table=analysis_trial_table,
    )

    return EventAlignmentValidationResult(
        output_dir=output_dir,
        event_table_path=event_table_path,
        analysis_trial_table_path=analysis_trial_table_path,
        validation_checks_path=validation_checks_path,
        dff_length_path=dff_length_path,
        raw_h5_health_path=raw_h5_health_path,
        physical_input_health_path=physical_input_health_path,
        start_end_alignment_path=start_end_alignment_path,
        stim_duration_summary_path=stim_duration_summary_path,
        stim_duration_outliers_path=stim_duration_outliers_path,
        report_path=report_path,
        event_table=event_table,
        analysis_trial_table=analysis_trial_table,
        validation_checks=validation_checks,
        dff_length_checks=dff_length_checks,
        raw_h5_health=raw_h5_health,
        physical_input_health=physical_input_health,
        start_end_alignment=start_end_alignment,
        stim_duration_summary=stim_duration_summary,
        stim_duration_outliers=stim_duration_outliers,
    )


def build_arg_parser() -> argparse.ArgumentParser:
    """Build CLI parser."""
    parser = argparse.ArgumentParser(description="Validate event alignment, voltage health, and dF/F frame mapping.")
    parser.add_argument("--data-dir", required=True, help="Session data directory.")
    parser.add_argument("--output-dir", default=None, help="Output directory. Defaults to data-dir.")
    parser.add_argument(
        "--skip-voltage-csv-scan",
        action="store_true",
        help="Skip chunked scan of the large physical voltage CSV inputs.",
    )
    return parser


def main() -> None:
    """Command-line entry point."""
    args = build_arg_parser().parse_args()
    result = run_event_alignment_validation(
        data_dir=args.data_dir,
        output_dir=args.output_dir,
        scan_voltage_csv_inputs=not args.skip_voltage_csv_scan,
    )
    print(f"Saved event table: {result.event_table_path}")
    print(f"Saved trial-level analysis table: {result.analysis_trial_table_path}")
    print(f"Saved validation checks: {result.validation_checks_path}")
    print(f"Saved report: {result.report_path}")
    print("\nHigh-level checks:")
    print(result.validation_checks.to_string(index=False))


if __name__ == "__main__":
    main()
