"""
Compare a Bonsai task-definition CSV with the stimulus CSV generated by Bonsai.

This module is intended for the closed-loop two-photon stimulus logs where:

1. ``sensorimotor_mismatch_example.csv`` is the task file read by Bonsai.
2. ``orientations_orientations0.csv`` is the stimulus output written by Bonsai.
3. ``orientations_logger.csv`` optionally contains StimStart/StimEnd events and
   is used to recover the actual Bonsai output timing.

The analysis produces:

* A side-by-side timeline figure for the task CSV and Bonsai output.
* A dedicated block-2 comparison figure.
* CSV summaries for the whole task, per-block structure, and quality checks.

The public entry point is ``run_analysis``. It can be imported from a notebook or
called from the command line:

    python ali_analysis/task_vs_bonsai_analysis.py --data-dir /path/to/session

The plotting code intentionally disables vertical grid lines and hides the top
and right spines to keep the figures clean.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Rectangle


TASK_CSV = "sensorimotor_mismatch_example.csv"
BONSAI_CSV = "orientations_orientations0.csv"
LOGGER_CSV = "orientations_logger.csv"

MAIN_FIGURE_NAME = "task_vs_bonsai_timeline.pdf"
BLOCK2_FIGURE_NAME = "block2_task_vs_bonsai_comparison.pdf"
SUMMARY_CSV_NAME = "task_vs_bonsai_summary.csv"
BLOCK_SUMMARY_CSV_NAME = "task_vs_bonsai_block_summary.csv"
CHECKS_CSV_NAME = "task_vs_bonsai_checks.csv"


RENAME_TO_CANONICAL = {
    "BlockNumber": "Block_Number",
    "BlockLabel": "Block_Label",
    "TrialNumber": "Trial_Number",
    "SequenceNumber": "Sequence_Number",
    "TrialInSequence": "Trial_In_Sequence",
    "SpatialFrequency": "Spatial_Frequency",
    "TemporalFrequency": "Temporal_Frequency",
    "TrialType": "Trial_Type",
    "BlockType": "Block_Type",
}

NUMERIC_COLS = [
    "Block_Number",
    "Block_Duration_Minutes",
    "Trial_Number",
    "Sequence_Number",
    "Trial_In_Sequence",
    "Contrast",
    "Delay",
    "DiameterX",
    "DiameterY",
    "Duration",
    "Orientation",
    "Spatial_Frequency",
    "Temporal_Frequency",
    "X",
    "Y",
]

ODDBALL_MAP = {
    "omission": "omission",
    "motor_omission": "omission",
    "halt": "halt",
    "motor_halt": "halt",
    "motor_orientation_90": "orientation_90",
    "motor_orientation_45": "orientation_45",
}
ODDBALL_ORDER = ["omission", "halt", "orientation_90", "orientation_45"]
ODDBALL_COLORS = {
    "omission": "#2ca25f",
    "halt": "#756bb1",
    "orientation_90": "#fdae61",
    "orientation_45": "#d73027",
}

ORIENTATION_TRIAL_TYPES = [
    "single",
    "standard",
    "prerecorded",
    "motor_orientation_45",
    "motor_orientation_90",
    "rf_mapping",
]
BASE_ORIS = [0.0, 22.5, 45.0, 67.5, 90.0, 112.5, 135.0, 157.5]

DISPLAY_NAMES = {
    "standard_control": "Control\n(Standard\nstimuli)",
    "motor_oddball": "Sensory-Motor\nMismatch\n(Motor\ncoupling)",
    "sequential_control_block": "Control\n(Shuffled\nsequences)",
    "jitter_control": "Control\n(Duration\ntuning)",
    "open_loop_prerecorded": "Control\n(Pre-recorded)",
    "movie": "Movie",
    "rf_mapping": "RF Mapping\n(Spatial\ntuning)",
}

BLOCK_COLORS = {
    "standard_control": "#d7e8f7",
    "motor_oddball": "#ffe0b2",
    "sequential_control_block": "#eeeeee",
    "jitter_control": "#f9e4d8",
    "open_loop_prerecorded": "#d7d8f7",
    "movie": "#d9d9d9",
    "rf_mapping": "#fff9b0",
}

SOURCE_COLORS = {
    "Task CSV read by Bonsai": "#2b6f9f",
    "Bonsai generated output": "#cc4c02",
}


@dataclass(frozen=True)
class AnalysisResult:
    """Paths and summary tables produced by ``run_analysis``."""

    main_figure_path: Path
    block2_figure_path: Path
    summary_csv_path: Path
    block_summary_csv_path: Path
    checks_csv_path: Path
    overall_summary: pd.DataFrame
    task_block_summary: pd.DataFrame
    bonsai_block_summary: pd.DataFrame
    block2_summary: pd.DataFrame
    block2_difference: pd.DataFrame
    checks: pd.DataFrame


def format_deg(value: float) -> str:
    """Format orientation ticks without unnecessary decimal places."""
    if pd.isna(value):
        return ""
    if np.isclose(value, round(value), atol=1e-6):
        return f"{int(round(value))}"
    return f"{value:g}"


def style_axis(ax: plt.Axes, y_grid: bool = True) -> None:
    """Apply the shared figure style.

    Vertical grid lines are always disabled. Horizontal grid lines are optional,
    because block bars look cleaner without them.
    """
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.xaxis.grid(False)
    if y_grid:
        ax.yaxis.grid(True, linestyle="--", linewidth=0.5, alpha=0.45)
    else:
        ax.yaxis.grid(False)
    ax.tick_params(axis="both", labelsize=10)


def add_minutes_axis(ax: plt.Axes) -> plt.Axes:
    """Add a secondary top x-axis in minutes for an axis whose units are seconds."""
    secax = ax.secondary_xaxis("top", functions=(lambda x: x / 60, lambda x: x * 60))
    secax.set_xlabel("Time (min)", fontsize=11)
    secax.spines["top"].set_visible(False)
    secax.xaxis.grid(False)
    secax.tick_params(axis="x", labelsize=9, length=0)
    return secax


def load_logger_timing(logger_path: Path) -> Optional[pd.DataFrame]:
    """Load StimStart/StimEnd timing from ``orientations_logger.csv``.

    Returns
    -------
    pandas.DataFrame or None
        A table keyed by stimulus ``Id`` with start/end frames and timestamps.
        ``None`` is returned when the logger file does not exist.
    """
    if not logger_path.exists():
        return None

    logger = pd.read_csv(logger_path)
    values = logger["Value"].astype(str)

    starts = logger.loc[values.str.startswith("StimStart-"), ["Frame", "Timestamp", "Value"]].copy()
    starts["Id"] = starts["Value"].str.replace("StimStart-", "", regex=False)
    starts = starts.rename(columns={"Frame": "Logger_Start_Frame", "Timestamp": "Logger_Start_sec_abs"})

    ends = logger.loc[values.str.startswith("StimEnd-"), ["Frame", "Timestamp", "Value"]].copy()
    ends["Id"] = ends["Value"].str.replace("StimEnd-", "", regex=False)
    ends = ends.rename(columns={"Frame": "Logger_End_Frame", "Timestamp": "Logger_End_sec_abs"})

    timing = starts[["Id", "Logger_Start_Frame", "Logger_Start_sec_abs"]].merge(
        ends[["Id", "Logger_End_Frame", "Logger_End_sec_abs"]], on="Id", how="outer"
    )
    timing["Logger_Duration_sec"] = timing["Logger_End_sec_abs"] - timing["Logger_Start_sec_abs"]
    return timing


def load_stimulus_csv(
    csv_path: Path,
    source_label: str,
    logger_timing: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Load one stimulus CSV and normalize it to a common schema.

    The task CSV and the Bonsai output CSV use slightly different column names.
    This function renames both into the same canonical names. It also computes
    start/end times from the CSV ``Duration`` column. If logger timing is passed
    and the CSV has an ``Id`` column, logger StimStart/StimEnd timing is used for
    plotting because that reflects Bonsai's actual generated output.
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing CSV file: {csv_path}")

    df = pd.read_csv(csv_path).rename(columns=RENAME_TO_CANONICAL)
    df["Source"] = source_label

    for col in NUMERIC_COLS:
        if col not in df.columns:
            df[col] = np.nan
        df[col] = pd.to_numeric(df[col], errors="coerce")

    for col in ["Block_Label", "Trial_Type", "Block_Type"]:
        if col not in df.columns:
            df[col] = "unknown"
        df[col] = df[col].astype(str)

    df["Duration_sec"] = df["Duration"].fillna(0)
    df["Csv_Time_sec"] = df["Duration_sec"].shift(fill_value=0).cumsum()
    df["Csv_End_sec"] = df["Csv_Time_sec"] + df["Duration_sec"]

    # The task CSV stores orientations in degrees. Bonsai output from this run
    # stores orientations in radians. Detect radians and convert for plotting.
    finite_oris = df["Orientation"].dropna().abs()
    orientation_in_radians = finite_oris.max() <= (2 * np.pi + 1e-6) if not finite_oris.empty else False
    df["Orientation_Deg"] = np.rad2deg(df["Orientation"]) if orientation_in_radians else df["Orientation"]
    df["Orientation_Deg"] = df["Orientation_Deg"].round(6)
    df["Orientation_Mod180"] = np.mod(df["Orientation_Deg"], 180)
    df["Orientation_Units_Source"] = "radians converted to degrees" if orientation_in_radians else "degrees"

    df["Time_sec"] = df["Csv_Time_sec"]
    df["End_sec"] = df["Csv_End_sec"]
    df["Time_Source"] = "CSV Duration column"

    if logger_timing is not None and "Id" in df.columns:
        df = df.merge(logger_timing, on="Id", how="left")
        has_logger = df["Logger_Start_sec_abs"].notna() & df["Logger_End_sec_abs"].notna()
        if has_logger.any():
            t0 = df.loc[has_logger, "Logger_Start_sec_abs"].min()
            df.loc[has_logger, "Time_sec"] = df.loc[has_logger, "Logger_Start_sec_abs"] - t0
            df.loc[has_logger, "End_sec"] = df.loc[has_logger, "Logger_End_sec_abs"] - t0
            df.loc[has_logger, "Time_Source"] = "logger StimStart/StimEnd"
    else:
        for col in [
            "Logger_Start_Frame",
            "Logger_Start_sec_abs",
            "Logger_End_Frame",
            "Logger_End_sec_abs",
            "Logger_Duration_sec",
        ]:
            df[col] = np.nan

    df["Oddball_Type"] = df["Trial_Type"].map(ODDBALL_MAP)
    return df


def make_block_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Summarize each block: boundaries, durations, UUID trials, and trial types."""
    block_summary = (
        df.groupby(["Block_Number", "Block_Label", "Block_Type"], dropna=False, as_index=False)
        .agg(
            Start_sec=("Time_sec", "min"),
            End_sec=("End_sec", "max"),
            Row_Count=("Trial_Number", "size"),
            Trial_Start=("Trial_Number", "min"),
            Trial_End=("Trial_Number", "max"),
            Declared_Min=("Block_Duration_Minutes", "first"),
            Csv_Duration_sec=("Duration_sec", "sum"),
            Logger_Duration_sec=("Logger_Duration_sec", "sum"),
            Time_Source=("Time_Source", "first"),
        )
        .sort_values("Block_Number")
        .reset_index(drop=True)
    )
    block_summary["Timeline_Span_sec"] = block_summary["End_sec"] - block_summary["Start_sec"]
    block_summary["Csv_Duration_min"] = block_summary["Csv_Duration_sec"] / 60
    block_summary["Timeline_Span_min"] = block_summary["Timeline_Span_sec"] / 60

    trial_counts = df.groupby(["Block_Number", "Trial_Type"], dropna=False).size().unstack(fill_value=0)
    return block_summary.merge(trial_counts, on="Block_Number", how="left")


def make_source_summary(df: pd.DataFrame, source_label: str) -> dict:
    """Summarize one complete stimulus table."""
    span_sec = df["End_sec"].max() - df["Time_sec"].min()
    counts = df["Trial_Type"].value_counts()
    odd_counts = df["Oddball_Type"].value_counts()
    logger_rows = int(df["Logger_Start_sec_abs"].notna().sum()) if "Logger_Start_sec_abs" in df.columns else 0

    return {
        "Source": source_label,
        "Rows": int(len(df)),
        "Unique_Ids": int(df["Id"].nunique()) if "Id" in df.columns else np.nan,
        "Blocks": int(df["Block_Number"].nunique(dropna=True)),
        "Trial_Start": int(df["Trial_Number"].min()),
        "Trial_End": int(df["Trial_Number"].max()),
        "Csv_Duration_sec": float(df["Duration_sec"].sum()),
        "Plotted_Span_sec": float(span_sec),
        "Time_Source": df["Time_Source"].mode().iloc[0],
        "Logger_Matched_Rows": logger_rows,
        "standard": int(counts.get("standard", 0)),
        "single": int(counts.get("single", 0)),
        "prerecorded": int(counts.get("prerecorded", 0)),
        "rf_mapping": int(counts.get("rf_mapping", 0)),
        "omission": int(odd_counts.get("omission", 0)),
        "halt": int(odd_counts.get("halt", 0)),
        "orientation_90": int(odd_counts.get("orientation_90", 0)),
        "orientation_45": int(odd_counts.get("orientation_45", 0)),
    }


def block2_metrics(df: pd.DataFrame, label: str) -> dict:
    """Compute the metrics used in the block-2 comparison table."""
    block = df[df["Block_Number"].eq(2)].copy()
    odd_counts = block["Oddball_Type"].value_counts()
    counts = block["Trial_Type"].value_counts()
    span_sec = block["End_sec"].max() - block["Time_sec"].min()

    return {
        "Source": label,
        "Rows": int(len(block)),
        "Unique_Ids": int(block["Id"].nunique()) if "Id" in block.columns else np.nan,
        "Trial_Start": int(block["Trial_Number"].min()),
        "Trial_End": int(block["Trial_Number"].max()),
        "Declared_Min": float(block["Block_Duration_Minutes"].dropna().iloc[0])
        if block["Block_Duration_Minutes"].notna().any()
        else np.nan,
        "Csv_Duration_sec": float(block["Duration_sec"].sum()),
        "Plotted_Span_sec": float(span_sec),
        "standard": int(counts.get("standard", 0)),
        "omission": int(odd_counts.get("omission", 0)),
        "halt": int(odd_counts.get("halt", 0)),
        "orientation_90": int(odd_counts.get("orientation_90", 0)),
        "orientation_45": int(odd_counts.get("orientation_45", 0)),
    }


def make_block2_difference_table(task_df: pd.DataFrame, bonsai_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return block-2 source summaries and Bonsai-minus-task differences."""
    task_metrics = block2_metrics(task_df, "Task CSV block 2")
    bonsai_metrics = block2_metrics(bonsai_df, "Bonsai output block 2")

    metric_specs = [
        ("Trials", "Rows", ",.0f"),
        ("Unique trial UUIDs", "Unique_Ids", ",.0f"),
        ("First Bonsai TrialNumber", "Trial_Start", ",.0f"),
        ("Last Bonsai TrialNumber", "Trial_End", ",.0f"),
        ("Standards", "standard", ",.0f"),
        ("Omissions", "omission", ",.0f"),
        ("Halts", "halt", ",.0f"),
        ("Orientation 90", "orientation_90", ",.0f"),
        ("Orientation 45", "orientation_45", ",.0f"),
        ("CSV duration sec", "Csv_Duration_sec", ".3f"),
        ("Plotted span sec", "Plotted_Span_sec", ".3f"),
    ]

    rows = []
    for label, key, fmt in metric_specs:
        task_value = task_metrics[key]
        bonsai_value = bonsai_metrics[key]
        diff = bonsai_value - task_value if pd.notna(task_value) and pd.notna(bonsai_value) else np.nan
        rows.append(
            {
                "Metric": label,
                "Task_Block2": task_value,
                "Bonsai_Output": bonsai_value,
                "Difference": diff,
                "Format": fmt,
            }
        )
    return pd.DataFrame(rows), pd.DataFrame([task_metrics, bonsai_metrics])


def make_quality_checks(task_df: pd.DataFrame, bonsai_df: pd.DataFrame, diff_table: pd.DataFrame) -> pd.DataFrame:
    """Create concise quality checks that flag the block-2 boundary mismatch."""
    row_diff = int(diff_table.loc[diff_table["Metric"].eq("Trials"), "Difference"].iloc[0])
    uuid_diff_value = diff_table.loc[diff_table["Metric"].eq("Unique trial UUIDs"), "Difference"].iloc[0]
    uuid_diff = int(uuid_diff_value) if pd.notna(uuid_diff_value) else np.nan
    last_trial_diff = int(diff_table.loc[diff_table["Metric"].eq("Last Bonsai TrialNumber"), "Difference"].iloc[0])

    return pd.DataFrame(
        [
            {
                "Check": "Task CSV Bonsai TrialNumber values are unique and monotonic",
                "Status": "OK"
                if task_df["Trial_Number"].is_unique and task_df["Trial_Number"].is_monotonic_increasing
                else "WARN",
                "Value": f"{task_df['Trial_Number'].min():.0f}-{task_df['Trial_Number'].max():.0f}",
            },
            {
                "Check": "Bonsai output TrialNumber values are unique and monotonic",
                "Status": "OK"
                if bonsai_df["Trial_Number"].is_unique and bonsai_df["Trial_Number"].is_monotonic_increasing
                else "WARN",
                "Value": f"{bonsai_df['Trial_Number'].min():.0f}-{bonsai_df['Trial_Number'].max():.0f}",
            },
            {
                "Check": "Bonsai output has one unique UUID per trial row",
                "Status": "OK"
                if "Id" in bonsai_df.columns and bonsai_df["Id"].nunique() == len(bonsai_df)
                else "WARN",
                "Value": f"unique_ids={bonsai_df['Id'].nunique() if 'Id' in bonsai_df.columns else 0:,}, rows={len(bonsai_df):,}",
            },
            {
                "Check": "Bonsai output rows matched to logger StimStart/StimEnd IDs",
                "Status": "OK"
                if bonsai_df["Logger_Start_sec_abs"].notna().all()
                and bonsai_df["Logger_End_sec_abs"].notna().all()
                else "WARN",
                "Value": f"{bonsai_df['Logger_Start_sec_abs'].notna().sum():,}/{len(bonsai_df):,}",
            },
            {
                "Check": "Block 2 trial row difference, Bonsai minus task CSV",
                "Status": "WARN" if row_diff != 0 else "OK",
                "Value": f"{row_diff:+d} trials",
            },
            {
                "Check": "Block 2 trial UUID difference, Bonsai minus task CSV",
                "Status": "WARN" if pd.isna(uuid_diff) or uuid_diff != 0 else "OK",
                "Value": "n/a" if pd.isna(uuid_diff) else f"{uuid_diff:+d} UUIDs",
            },
            {
                "Check": "Block 2 last Bonsai TrialNumber difference, Bonsai minus task CSV",
                "Status": "WARN" if last_trial_diff != 0 else "OK",
                "Value": f"{last_trial_diff:+d}",
            },
        ]
    )


def source_summary_lines(df: pd.DataFrame, source_label: str) -> list[str]:
    """Text lines used in the summary panel on the main figure."""
    summary = make_source_summary(df, source_label)
    counts = df["Trial_Type"].value_counts().head(6)
    top_types = ", ".join(f"{trial_type}: {count:,}" for trial_type, count in counts.items())
    oddball_text = (
        f"omission {summary['omission']:,}, halt {summary['halt']:,}, "
        f"90 {summary['orientation_90']:,}, 45 {summary['orientation_45']:,}"
    )
    uuid_text = "n/a" if pd.isna(summary["Unique_Ids"]) else f"{int(summary['Unique_Ids']):,}"

    return [
        f"Trials: {summary['Rows']:,}    Unique trial UUIDs: {uuid_text}    Blocks: {summary['Blocks']:,}",
        f"Bonsai TrialNumber range: {summary['Trial_Start']:,} to {summary['Trial_End']:,}",
        f"CSV duration sum: {summary['Csv_Duration_sec'] / 60:.2f} min",
        f"Plotted span: {summary['Plotted_Span_sec'] / 60:.2f} min ({summary['Time_Source']})",
        f"Oddball counts: {oddball_text}",
        f"Top trial types: {top_types}",
    ]


def plot_block_axis(ax: plt.Axes, block_summary: pd.DataFrame, title: str) -> None:
    """Draw block rectangles with labels."""
    for _, row in block_summary.iterrows():
        x0 = row["Start_sec"]
        width = row["End_sec"] - row["Start_sec"]
        block_type = row["Block_Type"]
        block_number = int(row["Block_Number"])
        duration_label = row["Declared_Min"] if pd.notna(row["Declared_Min"]) else row["Timeline_Span_min"]

        rect = Rectangle(
            (x0, 0),
            width,
            1,
            facecolor=BLOCK_COLORS.get(block_type, "#dddddd"),
            edgecolor="black",
            linewidth=0.8,
            alpha=0.75,
        )
        ax.add_patch(rect)

        if block_type == "movie":
            name = f"{DISPLAY_NAMES.get(block_type, block_type)}\n({row['Block_Label']})"
            fs = 9
        else:
            name = DISPLAY_NAMES.get(block_type, str(row["Block_Label"]))
            fs = 9 if width < 220 else 10

        duration_suffix = "target" if pd.notna(row["Declared_Min"]) else "logged"
        label = f"Block {block_number}\n{name}\n({duration_label:.2f} min {duration_suffix})"
        ax.text(
            x0 + width / 2,
            0.5,
            label,
            ha="center",
            va="center",
            fontsize=fs,
            weight="bold",
            bbox=dict(boxstyle="round,pad=0.22", facecolor="white", edgecolor="none", alpha=0.72),
            clip_on=True,
        )

    ax.set_ylim(0, 1)
    ax.set_yticks([])
    ax.set_ylabel("Blocks", fontsize=11)
    ax.set_title(title, weight="bold", pad=10, fontsize=14)
    style_axis(ax, y_grid=False)
    add_minutes_axis(ax)


def plot_orientation_axis(ax: plt.Axes, df: pd.DataFrame) -> None:
    """Draw orientation values over time."""
    palette = sns.color_palette("tab10", n_colors=len(BASE_ORIS))
    ori_color_map = {ori: palette[i] for i, ori in enumerate(BASE_ORIS)}

    plot_df = df[df["Block_Type"].ne("movie")].copy()
    ori_df = plot_df[plot_df["Trial_Type"].isin(ORIENTATION_TRIAL_TYPES)].dropna(subset=["Orientation_Deg"])

    for ori in sorted(ori_df["Orientation_Deg"].dropna().unique()):
        sub = ori_df[ori_df["Orientation_Deg"].eq(ori)]
        color_key = float(np.mod(ori, 180))
        label = f"{format_deg(color_key)} deg" if ori < 180 else None
        ax.scatter(
            sub["Time_sec"],
            sub["Orientation_Deg"],
            s=12,
            color=ori_color_map.get(color_key, "gray"),
            alpha=0.65,
            edgecolors="none",
            label=label,
            rasterized=True,
        )

    handles, labels = ax.get_legend_handles_labels()
    seen = set()
    uniq_handles, uniq_labels = [], []
    for handle, label in zip(handles, labels):
        if label and label not in seen:
            seen.add(label)
            uniq_handles.append(handle)
            uniq_labels.append(label)

    if uniq_handles:
        ax.legend(uniq_handles, uniq_labels, bbox_to_anchor=(1.01, 1), loc="upper left", frameon=False, fontsize=8)

    yticks = sorted(ori_df["Orientation_Deg"].dropna().unique())
    ax.set_yticks(yticks)
    ax.set_yticklabels([format_deg(y) for y in yticks], fontsize=9)
    ax.set_ylabel("Orientation\n(deg)", fontsize=11)
    ax.set_title("Grating orientations", weight="bold", pad=8, fontsize=13)
    style_axis(ax, y_grid=True)


def plot_oddball_axis(ax: plt.Axes, df: pd.DataFrame) -> None:
    """Draw oddball events over time."""
    plot_df = df[df["Block_Type"].ne("movie")].copy()
    oddball_df = plot_df[plot_df["Oddball_Type"].isin(ODDBALL_ORDER)].copy()

    for oddball_type in ODDBALL_ORDER:
        sub = oddball_df[oddball_df["Oddball_Type"].eq(oddball_type)]
        ax.scatter(
            sub["Time_sec"],
            [oddball_type] * len(sub),
            s=34,
            color=ODDBALL_COLORS[oddball_type],
            alpha=0.82,
            edgecolors="none",
            label=oddball_type,
            rasterized=True,
        )

    ax.set_ylabel("Oddball\ntype", fontsize=11)
    ax.set_title("Oddball events", weight="bold", pad=8, fontsize=13)
    ax.legend(loc="upper right", frameon=False, fontsize=9)
    style_axis(ax, y_grid=True)


def add_summary_panel(ax: plt.Axes, df: pd.DataFrame, source_label: str) -> None:
    """Add a text summary panel below a source timeline."""
    ax.axis("off")
    for spine in ax.spines.values():
        spine.set_visible(False)

    lines = source_summary_lines(df, source_label)
    ax.text(0.0, 0.98, "Summary", ha="left", va="top", fontsize=13, weight="bold", transform=ax.transAxes)
    ax.text(
        0.0,
        0.82,
        "\n".join(lines),
        ha="left",
        va="top",
        fontsize=10,
        linespacing=1.35,
        transform=ax.transAxes,
        family="DejaVu Sans Mono",
    )


def plot_source_timelines(
    task_df: pd.DataFrame,
    bonsai_df: pd.DataFrame,
    task_block_summary: pd.DataFrame,
    bonsai_block_summary: pd.DataFrame,
    output_path: Path,
    dpi: int,
) -> None:
    """Save the main side-by-side task-vs-output timeline figure."""
    fig = plt.figure(figsize=(62, 18), constrained_layout=True)
    gs = fig.add_gridspec(4, 2, height_ratios=[1.2, 1.05, 1.0, 0.75], hspace=0.22, wspace=0.16)

    configs = [
        (task_df, task_block_summary, "Task CSV read by Bonsai"),
        (bonsai_df, bonsai_block_summary, "Bonsai generated output"),
    ]

    for col, (source_df, block_summary, source_label) in enumerate(configs):
        ax_block = fig.add_subplot(gs[0, col])
        ax_ori = fig.add_subplot(gs[1, col], sharex=ax_block)
        ax_odd = fig.add_subplot(gs[2, col], sharex=ax_block)
        ax_summary = fig.add_subplot(gs[3, col])

        plot_block_axis(ax_block, block_summary, source_label)
        plot_orientation_axis(ax_ori, source_df)
        plot_oddball_axis(ax_odd, source_df)
        add_summary_panel(ax_summary, source_df, source_label)

        xmin = source_df["Time_sec"].min()
        xmax = source_df["End_sec"].max()
        for ax in [ax_block, ax_ori, ax_odd]:
            ax.set_xlim(xmin, xmax)
        ax_odd.set_xlabel("Time from start (sec)", fontsize=11)

    fig.suptitle("Task Definition vs Bonsai-Generated Stimulus Output", fontsize=18, weight="bold")
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def relative_block(df: pd.DataFrame, block_number: int = 2) -> pd.DataFrame:
    """Return one block with time reset to the block start."""
    block = df[df["Block_Number"].eq(block_number)].copy()
    t0 = block["Time_sec"].min()
    block["Rel_Time_sec"] = block["Time_sec"] - t0
    block["Rel_End_sec"] = block["End_sec"] - t0
    return block


def add_comparison_table(ax: plt.Axes, diff_table: pd.DataFrame) -> None:
    """Render the block-2 numeric comparison as a Matplotlib table."""
    ax.axis("off")
    table_rows = []
    for _, row in diff_table.iterrows():
        fmt = row["Format"]
        table_rows.append(
            [
                row["Metric"],
                f"{row['Task_Block2']:{fmt}}" if pd.notna(row["Task_Block2"]) else "n/a",
                f"{row['Bonsai_Output']:{fmt}}" if pd.notna(row["Bonsai_Output"]) else "n/a",
                f"{row['Difference']:+{fmt}}" if pd.notna(row["Difference"]) else "n/a",
            ]
        )

    table = ax.table(
        cellText=table_rows,
        colLabels=["Metric", "Task block 2", "Bonsai output", "Difference"],
        cellLoc="center",
        colLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9.5)
    table.scale(1, 1.25)

    for (row, col), cell in table.get_celld().items():
        cell.set_linewidth(0.35)
        if row == 0:
            cell.set_text_props(weight="bold")
            cell.set_facecolor("#f2f2f2")
        elif col == 0:
            cell.set_text_props(ha="left")


def plot_block2_comparison(
    task_df: pd.DataFrame,
    bonsai_df: pd.DataFrame,
    diff_table: pd.DataFrame,
    output_path: Path,
    dpi: int,
) -> None:
    """Save the dedicated block-2 comparison figure."""
    task_b2 = relative_block(task_df, block_number=2)
    bonsai_b2 = relative_block(bonsai_df, block_number=2)

    task_span = task_b2["Rel_End_sec"].max()
    bonsai_span = bonsai_b2["Rel_End_sec"].max()

    fig = plt.figure(figsize=(24, 16), constrained_layout=True)
    gs = fig.add_gridspec(4, 1, height_ratios=[0.75, 1.1, 1.1, 1.35], hspace=0.25)
    ax_extent = fig.add_subplot(gs[0, 0])
    ax_ori = fig.add_subplot(gs[1, 0], sharex=ax_extent)
    ax_odd = fig.add_subplot(gs[2, 0], sharex=ax_extent)
    ax_table = fig.add_subplot(gs[3, 0])

    y_positions = [1, 0]
    labels = ["Task CSV block 2", "Bonsai output"]
    spans = [task_span, bonsai_span]
    colors = [SOURCE_COLORS["Task CSV read by Bonsai"], SOURCE_COLORS["Bonsai generated output"]]
    ax_extent.barh(y_positions, spans, color=colors, alpha=0.75, height=0.42)
    for y, span in zip(y_positions, spans):
        ax_extent.text(span + 3, y, f"{span:.3f} sec", ha="left", va="center", fontsize=10, weight="bold")
    ax_extent.set_yticks(y_positions)
    ax_extent.set_yticklabels(labels, fontsize=10)
    ax_extent.set_title("Block 2 duration and boundary comparison", weight="bold", fontsize=14, pad=10)
    ax_extent.set_xlim(0, max(spans) * 1.05)
    style_axis(ax_extent, y_grid=False)
    add_minutes_axis(ax_extent)

    task_ori = task_b2[task_b2["Trial_Type"].isin(ORIENTATION_TRIAL_TYPES)].dropna(subset=["Orientation_Deg"])
    bonsai_ori = bonsai_b2[bonsai_b2["Trial_Type"].isin(ORIENTATION_TRIAL_TYPES)].dropna(subset=["Orientation_Deg"])
    ax_ori.scatter(
        task_ori["Rel_Time_sec"],
        task_ori["Orientation_Deg"],
        s=8,
        color=SOURCE_COLORS["Task CSV read by Bonsai"],
        alpha=0.35,
        edgecolors="none",
        label="Task CSV",
        rasterized=True,
    )
    ax_ori.scatter(
        bonsai_ori["Rel_Time_sec"],
        bonsai_ori["Orientation_Deg"],
        s=8,
        color=SOURCE_COLORS["Bonsai generated output"],
        alpha=0.35,
        edgecolors="none",
        label="Bonsai output",
        rasterized=True,
    )
    ax_ori.set_ylabel("Orientation\n(deg)", fontsize=11)
    ax_ori.set_title("Block 2 orientations", weight="bold", fontsize=13, pad=8)
    yticks = sorted(set(task_ori["Orientation_Deg"].dropna().unique()).union(set(bonsai_ori["Orientation_Deg"].dropna().unique())))
    ax_ori.set_yticks(yticks)
    ax_ori.set_yticklabels([format_deg(y) for y in yticks], fontsize=9)
    ax_ori.legend(loc="upper right", frameon=False, fontsize=10)
    style_axis(ax_ori, y_grid=True)

    y_map = {name: idx for idx, name in enumerate(ODDBALL_ORDER)}
    task_odd = task_b2[task_b2["Oddball_Type"].isin(ODDBALL_ORDER)].copy()
    bonsai_odd = bonsai_b2[bonsai_b2["Oddball_Type"].isin(ODDBALL_ORDER)].copy()
    task_odd["Oddball_Y"] = task_odd["Oddball_Type"].map(y_map).astype(float) - 0.13
    bonsai_odd["Oddball_Y"] = bonsai_odd["Oddball_Type"].map(y_map).astype(float) + 0.13

    for oddball_type in ODDBALL_ORDER:
        task_sub = task_odd[task_odd["Oddball_Type"].eq(oddball_type)]
        bonsai_sub = bonsai_odd[bonsai_odd["Oddball_Type"].eq(oddball_type)]
        ax_odd.scatter(
            task_sub["Rel_Time_sec"],
            task_sub["Oddball_Y"],
            s=42,
            marker="v",
            color=ODDBALL_COLORS[oddball_type],
            alpha=0.72,
            edgecolors="none",
            label=f"Task {oddball_type}" if oddball_type == ODDBALL_ORDER[0] else None,
            rasterized=True,
        )
        ax_odd.scatter(
            bonsai_sub["Rel_Time_sec"],
            bonsai_sub["Oddball_Y"],
            s=42,
            marker="^",
            color=ODDBALL_COLORS[oddball_type],
            alpha=0.92,
            edgecolors="black",
            linewidths=0.25,
            label=f"Bonsai {oddball_type}" if oddball_type == ODDBALL_ORDER[0] else None,
            rasterized=True,
        )

    ax_odd.set_yticks(list(y_map.values()))
    ax_odd.set_yticklabels(ODDBALL_ORDER, fontsize=10)
    ax_odd.set_ylabel("Oddball\ntype", fontsize=11)
    ax_odd.set_title("Block 2 oddball event placement", weight="bold", fontsize=13, pad=8)
    ax_odd.set_xlabel("Time from block 2 start (sec)", fontsize=11)
    ax_odd.legend(loc="upper right", frameon=False, fontsize=10)
    style_axis(ax_odd, y_grid=True)

    for ax in [ax_extent, ax_ori, ax_odd]:
        ax.set_xlim(0, max(task_span, bonsai_span) * 1.05)

    add_comparison_table(ax_table, diff_table)
    fig.suptitle("Block 2: Intended Task CSV vs Bonsai-Generated Output", fontsize=18, weight="bold")
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def run_analysis(
    data_dir: str | Path,
    output_dir: str | Path | None = None,
    task_csv: str = TASK_CSV,
    bonsai_csv: str = BONSAI_CSV,
    logger_csv: str = LOGGER_CSV,
    dpi: int = 300,
) -> AnalysisResult:
    """Run the complete task-vs-Bonsai comparison.

    Parameters
    ----------
    data_dir
        Session directory containing the task CSV, Bonsai output CSV, and
        optionally the logger CSV.
    output_dir
        Directory where figures and summary tables are written. If omitted,
        results are saved into ``data_dir``.
    task_csv, bonsai_csv, logger_csv
        File names relative to ``data_dir``. These defaults match the current
        session.
    dpi
        Resolution used for saved PDF figures.

    Returns
    -------
    AnalysisResult
        Object containing output paths and the summary DataFrames.
    """
    data_dir = Path(data_dir).expanduser().resolve()
    output_dir = data_dir if output_dir is None else Path(output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    sns.set_theme(style="whitegrid", context="talk")

    task_path = data_dir / task_csv
    bonsai_path = data_dir / bonsai_csv
    logger_path = data_dir / logger_csv

    logger_timing = load_logger_timing(logger_path)
    task_df = load_stimulus_csv(task_path, "Task CSV read by Bonsai")
    bonsai_df = load_stimulus_csv(bonsai_path, "Bonsai generated output", logger_timing=logger_timing)

    task_block_summary = make_block_summary(task_df)
    bonsai_block_summary = make_block_summary(bonsai_df)
    overall_summary = pd.DataFrame(
        [
            make_source_summary(task_df, "Task CSV read by Bonsai"),
            make_source_summary(bonsai_df, "Bonsai generated output"),
        ]
    )
    diff_table, block2_summary = make_block2_difference_table(task_df, bonsai_df)
    checks = make_quality_checks(task_df, bonsai_df, diff_table)

    main_figure_path = output_dir / MAIN_FIGURE_NAME
    block2_figure_path = output_dir / BLOCK2_FIGURE_NAME
    summary_csv_path = output_dir / SUMMARY_CSV_NAME
    block_summary_csv_path = output_dir / BLOCK_SUMMARY_CSV_NAME
    checks_csv_path = output_dir / CHECKS_CSV_NAME

    overall_summary.to_csv(summary_csv_path, index=False)
    pd.concat(
        [
            task_block_summary.assign(Source="Task CSV read by Bonsai"),
            bonsai_block_summary.assign(Source="Bonsai generated output"),
        ],
        ignore_index=True,
    ).to_csv(block_summary_csv_path, index=False)
    checks.to_csv(checks_csv_path, index=False)

    plot_source_timelines(task_df, bonsai_df, task_block_summary, bonsai_block_summary, main_figure_path, dpi)
    plot_block2_comparison(task_df, bonsai_df, diff_table, block2_figure_path, dpi)

    return AnalysisResult(
        main_figure_path=main_figure_path,
        block2_figure_path=block2_figure_path,
        summary_csv_path=summary_csv_path,
        block_summary_csv_path=block_summary_csv_path,
        checks_csv_path=checks_csv_path,
        overall_summary=overall_summary,
        task_block_summary=task_block_summary,
        bonsai_block_summary=bonsai_block_summary,
        block2_summary=block2_summary,
        block2_difference=diff_table.drop(columns="Format"),
        checks=checks,
    )


def build_arg_parser() -> argparse.ArgumentParser:
    """Build the command-line interface."""
    parser = argparse.ArgumentParser(
        description="Compare the task CSV read by Bonsai with the Bonsai-generated stimulus output."
    )
    parser.add_argument("--data-dir", required=True, help="Session folder containing the CSV files.")
    parser.add_argument("--output-dir", default=None, help="Folder for figures and summary CSVs. Defaults to data-dir.")
    parser.add_argument("--task-csv", default=TASK_CSV, help=f"Task CSV file name. Default: {TASK_CSV}")
    parser.add_argument("--bonsai-csv", default=BONSAI_CSV, help=f"Bonsai output CSV file name. Default: {BONSAI_CSV}")
    parser.add_argument("--logger-csv", default=LOGGER_CSV, help=f"Logger CSV file name. Default: {LOGGER_CSV}")
    parser.add_argument("--dpi", type=int, default=300, help="Figure resolution. Default: 300.")
    return parser


def main() -> None:
    """Command-line entry point."""
    args = build_arg_parser().parse_args()
    result = run_analysis(
        data_dir=args.data_dir,
        output_dir=args.output_dir,
        task_csv=args.task_csv,
        bonsai_csv=args.bonsai_csv,
        logger_csv=args.logger_csv,
        dpi=args.dpi,
    )

    print(f"Saved main figure: {result.main_figure_path}")
    print(f"Saved block 2 comparison figure: {result.block2_figure_path}")
    print(f"Saved summary CSV: {result.summary_csv_path}")
    print(f"Saved block summary CSV: {result.block_summary_csv_path}")
    print(f"Saved checks CSV: {result.checks_csv_path}")
    print("\nBlock 2 comparison:")
    print(result.block2_difference.to_string(index=False))
    print("\nData quality checks:")
    print(result.checks.to_string(index=False))


if __name__ == "__main__":
    main()
