# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 14:55:32 2026

@author: saminnaji3
"""

import os
import numpy as np
from modules import DffTraces
from modules.ReadResults import read_dff

# %%
subject = 'SA16_LG'
subject_id = 'SA16_'
date = '20260313/'
output_dir_onedrive = os.path.join('C:/Users/saminnaji3/OneDrive - Georgia Institute of Technology/2p imaging/Figures/', subject, 'all_figs', date)
output_dir_local = output_dir_onedrive
initial_path = 'C:\\Users\\saminnaji3\\Downloads'
# sa16
data_dates = ['20251215', '20251226', '20251227', '20251228', '20251229', '20251230', '20260103', '20260105' , '20260106', '20260107']
# sa18
data_dates = ['20251226', '20251227', '20251228', '20251229', '20251230', '20260103', '20260104', '20260105' , '20260106', '20260107']
# SA20
data_dates = ['20260120', '20260121']
# YH30
data_dates = ['20260130']
# sa18
data_dates = ['20260119', '20260107', '20260106']
# %% reading data 
list_session_data_path = []
for date in data_dates:
    list_session_data_path.append(os.path.join(initial_path, subject, subject_id + date))
# %%
# 2. Define the range of Tau values to test
# Your current default is 1.25; we will test around it
test_taus = [0.5, 0.75, 1.0, 1.25, 1.5, 2.0]

def run_tau_comparison(session_paths, taus):
    for path in session_paths:
        print(f"\n--- Testing Tau values for session: {os.path.basename(path)} ---")
        
        # Load the ops file for this session
        ops_path = os.path.join(path, 'suite2p', 'plane0', 'ops.npy')
        if not os.path.exists(ops_path):
            print(f"Skipping: {ops_path} not found.")
            continue
            
        ops = np.load(ops_path, allow_pickle=True).item()
        ops['save_path0'] = path
        
        # Load dff (this uses your existing ReadResults module)
        # We use 'manual_qc_results' as established in your main scripts
        try:
            dff = read_dff(ops, 'manual_qc_results')
        except:
            print("Could not find manual_qc_results. Make sure run_postprocess has been run.")
            continue

        # This triggers the 'if len(taus) > 1' logic in your DffTraces.py
        # It will run deconvolution for each tau and call analyze_spike_traces
        DffTraces.run(
            ops, 
            taus=taus, 
            plotting_neurons=[10, 50, 100], # Choose a few diverse neurons
            plot_without_smoothed=True
        )

if __name__ == "__main__":
    run_tau_comparison(list_session_data_path, test_taus)
    
# %%
import os
import numpy as np
import h5py
import plotly.graph_objects as go
from modules.ReadResults import read_dff
from suite2p.extraction.dcnv import oasis

def run_interactive_spike_validation(session_data_path, output_dir, tau, data_date, subset=None, fs=30):
    # 1. Load configuration and data
    ops = np.load(os.path.join(session_data_path, 'suite2p', 'plane0', 'ops.npy'), allow_pickle=True).item()
    ops['save_path0'] = session_data_path
    
    # Load baseline-corrected DFF
    dff = read_dff(ops, 'manual_qc_results') 
    
    # Load the spikes generated by OASIS
    spike_path = os.path.join(session_data_path, 'qc_results', 'spikes.h5')
    
        
    spikes_matrix = oasis(
        F=dff,
        batch_size=ops['batch_size'],
        tau=tau,
        fs=ops['fs'])

    # Determine which neurons to plot
    if subset is not None:
        neuron_indices = subset
        batch_size = len(subset)
    else:
        #neuron_indices = np.arange(dff.shape[0])
        neuron_indices = np.random.choice(np.arange(1, dff.shape[0] + 1), size=20, replace=False)
        batch_size = len(neuron_indices)

    time_min = np.arange(0, dff.shape[1]) / (fs * 60)
    
    # 2. Plotting Loop
    for itr_idx, i_start in enumerate(range(0, len(neuron_indices), batch_size)):
        i_end = min(i_start + batch_size, len(neuron_indices))
        current_batch = neuron_indices[i_start:i_end]
        
        fig = go.Figure()
        shift = 0
        curr_max = 0 
    
        for i in current_batch:
            # Normalize and shift based on your main.py logic
            curr_dff = dff[i, :] - np.nanmedian(dff[i, :])
            curr_spikes = spikes_matrix[i, :]
            
            curr_min = np.nanmin(curr_dff)
            shift = shift + np.abs(curr_min) + curr_max
            curr_max = np.nanmax(curr_dff)
            
            # Add DFF Trace
            fig.add_trace(go.Scatter(
                x=time_min, y=list(curr_dff + shift), 
                mode='lines', name=f'Neu {i}',
                line=dict(width=1, color='gray'), opacity=0.6
            ))
            
            # Add Spike Dots Superimposed
            spike_idx = np.where(curr_spikes > 0)[0]
            if len(spike_idx) > 0:
                fig.add_trace(go.Scatter(
                    x=time_min[spike_idx], y=list(curr_spikes[spike_idx] + shift),
                    mode='markers', marker=dict(color='red', size=3),
                    hoverinfo='text', text=[f'Neu: {i} | Amp: {a:.3f}' for a in curr_spikes[spike_idx]]
                ))

        # 3. Add Custom Zoom Buttons
        fig.update_layout(
            updatemenus=[dict(
                type="buttons",
                direction="right",
                x=0.1, y=1.15,
                buttons=[
                    dict(label="Reset View", method="relayout", args=[{"xaxis.range": [0, time_min[-1]]}]),
                    dict(label="Zoom 1-Min Window", method="relayout", args=[{"xaxis.range": [time_min[-1]/2, time_min[-1]/2 + 1]}])
                ]
            )],
            title=f'Spike Validation - {data_date} (Neurons {current_batch[0]}-{current_batch[-1]})',
            xaxis_title='Time (min)', yaxis_title='Stacked Activity',
            template='plotly_white', showlegend=False
        )
              
        save_name = f"{data_date}_spike_val_subset_{itr_idx}_{tau}.html"
        fig.write_html(os.path.join(output_dir, save_name))
        print(f"Saved: {save_name}")

# %%

example_neurons = [10, 25, 33, 45, 60, 72, 85, 99, 120, 140, 155, 170, 185, 200, 215, 230, 245, 260, 275, 300]

data_date = '20260216'
session_path = r'C:\Users\saminnaji3\Downloads\SA20_WT\SA20_20260216'

output_dir = 'C:/Users/saminnaji3/OneDrive - Georgia Institute of Technology/2p imaging/Figures/' + subject + '/RawTraces/All_ROIs/'
data_dates = ['20260119', '20260107', '20260106']



test_taus = [0.5, 0.75, 1.0, 1.25, 1.5, 2.0]

for data_date, path in zip(data_dates, list_session_data_path):
    print(f"\n--- Testing Tau values for session: {os.path.basename(path)} ---")
    
    # Load the ops file for this session
    ops_path = os.path.join(path, 'suite2p', 'plane0', 'ops.npy')
    if not os.path.exists(ops_path):
        print(f"Skipping: {ops_path} not found.")
        continue
        
    ops = np.load(ops_path, allow_pickle=True).item()
    ops['save_path0'] = path
    
    # Load dff (this uses your existing ReadResults module)
    # We use 'manual_qc_results' as established in your main scripts
    try:
        dff = read_dff(ops, 'manual_qc_results')
    except:
        print("Could not find manual_qc_results. Make sure run_postprocess has been run.")
        continue

    # This triggers the 'if len(taus) > 1' logic in your DffTraces.py
    # It will run deconvolution for each tau and call analyze_spike_traces
    subset = np.random.choice(np.arange(1, dff.shape[0] + 1), size=20, replace=False)
    for tau in test_taus:
        run_interactive_spike_validation(path, output_dir, tau, data_date, subset=subset, fs=30)

